using System.Text;

namespace SchemaPoc;

/// <summary>SchemaDesc → 强类型 C#(模块 1 §6 产物 1/7/8 的 PoC:类型、注册引导、SchemaHash 常量)。</summary>
public static class CSharpEmitter
{
    public static string Emit(SchemaDesc schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> SchemaPoc 生成;事实源 = Protos/game/game.proto,请勿手改。</auto-generated>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ExcelDbEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace Game.Configs");
        sb.AppendLine("{");

        foreach (var e in schema.Enums)
        {
            sb.AppendLine($"    public enum {e.Name}");
            sb.AppendLine("    {");
            foreach (var (number, name, display) in e.Values.OrderBy(v => v.Number))
            {
                var comment = display.Length > 0 ? $" // {display}" : "";
                sb.AppendLine($"        {EnumValueName(e.Name, name)} = {number},{comment}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var shape in schema.Shapes)
            EmitClass(sb, schema, shape, isAsset: false);
        foreach (var table in schema.Tables)
            EmitClass(sb, schema, table, table.IsAsset);

        sb.AppendLine("    public static class GameSchemaRegistry");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const ulong SchemaHash = 0x{schema.SchemaHash:X16}UL;");
        sb.AppendLine("        public static readonly (int Id, string Name, Type RuntimeType)[] Tables =");
        sb.AppendLine("        {");
        foreach (var t in schema.Tables.OrderBy(t => t.Id))
            sb.AppendLine($"            ({t.Id}, \"{t.Name}\", typeof({t.Name})),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitClass(StringBuilder sb, SchemaDesc schema, TableDesc msg, bool isAsset)
    {
        // ASSET 与 EMBEDDED 均为普通 C# 类:库定位 Unity 无关,资产语义经注册引导承载(M2 D4/Δ11)。
        sb.AppendLine($"    /// <summary>{msg.DisplayName}{(isAsset ? $"(表 id {msg.Id})" : "")}</summary>");
        sb.AppendLine($"    public partial class {msg.Name}");
        sb.AppendLine("    {");
        foreach (var f in msg.Fields)
            EmitMember(sb, schema, f);
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static void EmitMember(StringBuilder sb, SchemaDesc schema, FieldDesc f)
    {
        var member = Pascal(f.Name);
        var (type, init) = MemberType(schema, f);
        var comment = f.Shape switch
        {
            ValueShape.Union => $" // union: {string.Join(" | ", f.Children.Select(c => ShortType(c.TypeName)))}",
            ValueShape.Expression => $" // expr({f.ExprResult.Replace("Expr", "").ToLowerInvariant()}), symbols = {ShortType(f.ExprSymbols)}",
            ValueShape.Weighted => " // weighted 子表",
            ValueShape.ChildTable => " // 子表",
            ValueShape.StructListSingleCell => $" // 单 cell join[{string.Join(" ", f.Format.Separators)}]",
            _ => "",
        };
        sb.AppendLine($"        public {type} {member}{init};{comment}");
    }

    static (string Type, string Init) MemberType(SchemaDesc schema, FieldDesc f)
    {
        string Elem() => ShortType(f.TypeName);
        switch (f.Shape)
        {
            case ValueShape.Scalar:
                return (f.TypeName, ScalarInit(f.TypeName, f.DefaultValue));
            case ValueShape.Enum when !f.Repeated:
                return (ShortType(f.TypeName), "");
            case ValueShape.ScalarList:
                return ($"List<{ShortType(f.TypeName)}>", " = new()");
            case ValueShape.StructSingleCell or ValueShape.StructExpanded:
                return (Elem(), " = new()");
            case ValueShape.ChildTable or ValueShape.StructListSingleCell:
                return ($"List<{Elem()}>", " = new()");
            case ValueShape.Weighted:
                return ($"WeightedList<{Elem()}>", " = new()");
            case ValueShape.Map:
                return ($"Dictionary<{ShortType(f.MapKeyType)}, {ShortType(f.MapValueType)}>", " = new()");
            case ValueShape.Union:
                return ("object", "");
            case ValueShape.Expression:
                var t = f.ExprResult switch { "ExprInt" => "int", "ExprBool" => "bool", _ => "float" };
                return ($"Expression<{t}>", "");
            case ValueShape.InternalRef:
                return (f.RefTable.Length > 0 ? $"Ref<{f.RefTable}>" : "Ref<object>", "");
            case ValueShape.UnityRef: return ("UnityRef", "");
            case ValueShape.LocalizedRef: return ("LocalizedTextRef", "");
            case ValueShape.Curve: return ("Curve", " = new()");
            default: return ("object", "");
        }
    }

    static string ScalarInit(string csType, string defaultValue)
    {
        if (defaultValue.Length == 0) return csType == "string" ? " = \"\"" : "";
        return csType switch
        {
            "bool" => $" = {(defaultValue.Equals("TRUE", StringComparison.OrdinalIgnoreCase) ? "true" : "false")}",
            "string" => $" = \"{defaultValue}\"",
            "float" => $" = {defaultValue}f",
            _ => $" = {defaultValue}",
        };
    }

    static string ShortType(string fullName)
    {
        var name = fullName.Contains('.') ? fullName[(fullName.LastIndexOf('.') + 1)..] : fullName;
        return name;
    }

    public static string Pascal(string snake)
    {
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    }

    static string EnumValueName(string enumName, string valueName)
    {
        var prefix = string.Concat(enumName.Select((c, i) => i > 0 && char.IsUpper(c) ? "_" + c : c.ToString())).ToUpperInvariant() + "_";
        var v = valueName.StartsWith(prefix, StringComparison.Ordinal) ? valueName[prefix.Length..] : valueName;
        return Pascal(v.ToLowerInvariant());
    }
}
