using ExcelDb.Core.Diagnostics;
using ExcelDb.Pipeline;
using ExcelDb.Tooling.Plans;
using System.Reflection;
using Xunit;

namespace ExcelDb.ProjectHub.Windows.Tests;

public sealed class ProjectHubFormTests
{
    [Fact]
    public void HomePage_HasExactlyFourArtifactCardsAndMeaningfulActions()
    {
        Exception? failure = null;
        var thread = new Thread(() =>
        {
            try
            {
                using var form = new ProjectHubForm(
                    new UnusedProjectService(),
                    string.Empty,
                    new LauncherStateStore(Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"), "state.json")),
                    new UnusedShell());
                Assert.Equal(
                    ["Schema", "Excel", "Generated C#", "Generated Bytes"],
                    form.ArtifactCards.Select(static card => card.ArtifactName));
                Assert.Equal(4, Descendants(form).OfType<ArtifactCardControl>().Count());
                var buttonTexts = Descendants(form).OfType<Button>().Select(static button => button.Text).ToHashSet(StringComparer.Ordinal);
                Assert.Contains("初始化项目", buttonTexts);
                Assert.Contains("重新生成 C# 和 Excel", buttonTexts);
                Assert.Contains("修复 Proto 依赖", buttonTexts);
                Assert.Contains("项目设置", buttonTexts);
                Assert.DoesNotContain("Config", form.ArtifactCards.Select(static card => card.ArtifactName));
                Assert.DoesNotContain("Data", form.ArtifactCards.Select(static card => card.ArtifactName));
                Assert.DoesNotContain("Build", form.ArtifactCards.Select(static card => card.ArtifactName));
            }
            catch (Exception exception)
            {
                failure = exception;
            }
        });
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        Assert.True(thread.Join(TimeSpan.FromSeconds(10)), "STA form smoke test timed out.");
        if (failure is not null)
            throw new AggregateException(failure);
    }

    [Fact]
    public void Switching_projects_replaces_the_report_projection_instead_of_reusing_the_previous_path()
    {
        RunSta(() =>
        {
            var root = CreateTestRoot();
            try
            {
                var first = Path.Combine(root, "first");
                var second = Path.Combine(root, "second");
                Directory.CreateDirectory(first);
                Directory.CreateDirectory(second);
                var firstReport = Path.Combine(first, ".exceldb", "reports", "first.json");
                Directory.CreateDirectory(Path.GetDirectoryName(firstReport)!);
                File.WriteAllText(firstReport, "{}");
                var service = new UnusedProjectService(location =>
                    string.Equals(location.Path, first, StringComparison.OrdinalIgnoreCase)
                        ? Inspection(first, firstReport)
                        : Inspection(second, latestReportPath: null));
                using var form = CreateForm(service, root);

                Inspect(form, first);
                Assert.Equal(firstReport, CurrentReportPath(form));

                Inspect(form, second);

                Assert.Null(CurrentReportPath(form));
                Assert.Equal(second, CurrentInspection(form)?.ProjectRoot);
                Assert.False(OpenReportButton(form).Enabled);
            }
            finally
            {
                Directory.Delete(root, recursive: true);
            }
        });
    }

    [Fact]
    public void Failed_inspection_of_another_project_clears_the_previous_project_and_report()
    {
        RunSta(() =>
        {
            var root = CreateTestRoot();
            try
            {
                var first = Path.Combine(root, "first");
                var failing = Path.Combine(root, "failing");
                Directory.CreateDirectory(first);
                Directory.CreateDirectory(failing);
                var firstReport = Path.Combine(first, ".exceldb", "reports", "first.json");
                Directory.CreateDirectory(Path.GetDirectoryName(firstReport)!);
                File.WriteAllText(firstReport, "{}");
                var service = new UnusedProjectService(location =>
                {
                    if (string.Equals(location.Path, failing, StringComparison.OrdinalIgnoreCase))
                        throw new IOException("simulated inspection failure");
                    return Inspection(first, firstReport);
                });
                using var form = CreateForm(service, root);
                Inspect(form, first);
                Assert.Equal(firstReport, CurrentReportPath(form));

                var exception = Assert.Throws<IOException>(() => Inspect(form, failing));

                Assert.Equal("simulated inspection failure", exception.Message);
                Assert.Null(CurrentReportPath(form));
                Assert.Null(CurrentInspection(form));
                Assert.False(OpenReportButton(form).Enabled);
            }
            finally
            {
                Directory.Delete(root, recursive: true);
            }
        });
    }

    [Fact]
    public void Pending_rows_inspection_enables_prepare_and_exposes_why_convert_is_disabled()
    {
        RunSta(() =>
        {
            var root = CreateTestRoot();
            try
            {
                const string convertDisabledReason = "存在未分配 RowGuid 的新增行；请先准备新增行身份。";
                Directory.CreateDirectory(Path.Combine(root, ".exceldb"));
                var service = new UnusedProjectService(_ => PendingRowsInspection(root, convertDisabledReason));
                using var form = CreateForm(service, root);

                Inspect(form, root);

                var prepareRows = PrivateButton(form, "_prepareRows");
                var convert = PrivateButton(form, "_convert");
                var toolTip = (ToolTip)(PrivateField(form, "_toolTip")
                    ?? throw new InvalidOperationException("ProjectHubForm._toolTip was null."));
                var availabilitySummary = (Label)(PrivateField(form, "_availabilitySummary")
                    ?? throw new InvalidOperationException("ProjectHubForm._availabilitySummary was null."));

                Assert.Equal(ProjectStatus.PendingRows, CurrentInspection(form)?.Status);
                Assert.True(prepareRows.Enabled);
                Assert.False(convert.Enabled);
                Assert.Equal(convertDisabledReason, convert.AccessibleDescription);
                Assert.Equal(convertDisabledReason, toolTip.GetToolTip(convert));
                Assert.Contains("生成 bytes", availabilitySummary.Text, StringComparison.Ordinal);
                Assert.Contains(convertDisabledReason, availabilitySummary.Text, StringComparison.Ordinal);
            }
            finally
            {
                Directory.Delete(root, recursive: true);
            }
        });
    }

    [Fact]
    public void Opening_a_recognized_project_requests_the_explicit_owned_attribute_repair()
    {
        RunSta(() =>
        {
            var root = CreateTestRoot();
            try
            {
                Directory.CreateDirectory(Path.Combine(root, ".exceldb"));
                var repairCalls = 0;
                var service = new UnusedProjectService(
                    _ => Inspection(root, latestReportPath: null),
                    _ =>
                    {
                        repairCalls++;
                        return OperationReport.Success("project-repair-attributes", "test", applied: true);
                    });
                using var form = CreateForm(service, root);

                Inspect(form, root);

                Assert.Equal(1, repairCalls);
            }
            finally
            {
                Directory.Delete(root, recursive: true);
            }
        });
    }

    private static IEnumerable<Control> Descendants(Control parent)
    {
        foreach (Control child in parent.Controls)
        {
            yield return child;
            foreach (var descendant in Descendants(child))
                yield return descendant;
        }
    }

    private static ProjectHubForm CreateForm(IExcelDbProjectService service, string root) =>
        new(
            service,
            string.Empty,
            new LauncherStateStore(Path.Combine(root, "launcher-state.json")),
            new UnusedShell());

    private static ProjectInspection Inspection(string root, string? latestReportPath)
    {
        var unavailable = new ProjectActionAvailability(false, "test");
        var actions = new ProjectActions(
            unavailable,
            unavailable,
            unavailable,
            unavailable,
            unavailable,
            unavailable,
            unavailable,
            unavailable,
            unavailable);
        return new ProjectInspection(
            root,
            Path.Combine(root, ".exceldb", "project.json"),
            ProjectStatus.Ready,
            new ProjectArtifactInspection("Schema", Path.Combine(root, "Schema"), "Available", 1),
            new ProjectArtifactInspection("Excel", Path.Combine(root, "Excel"), "Available", 1),
            new ProjectArtifactInspection("Generated C#", Path.Combine(root, "Generated", "CSharp"), "Generated", 1),
            new ProjectArtifactInspection("Generated Bytes", Path.Combine(root, "Generated", "Bytes"), "Available", 1),
            actions,
            [],
            latestReportPath,
            Path.Combine(root, ".exceldb", "recovery"),
            Path.Combine(root, ".exceldb"));
    }

    private static ProjectInspection PendingRowsInspection(string root, string convertDisabledReason)
    {
        var enabled = new ProjectActionAvailability(true);
        var unavailable = new ProjectActionAvailability(false, "test");
        var actions = new ProjectActions(
            unavailable,
            enabled,
            enabled,
            enabled,
            enabled,
            enabled,
            new ProjectActionAvailability(false, convertDisabledReason),
            unavailable,
            enabled);
        return new ProjectInspection(
            root,
            Path.Combine(root, ".exceldb", "project.json"),
            ProjectStatus.PendingRows,
            new ProjectArtifactInspection("Schema", Path.Combine(root, "Schema"), "Ready: 1 table", 1),
            new ProjectArtifactInspection("Excel", Path.Combine(root, "Excel"), "1 row needs identity", 1),
            new ProjectArtifactInspection("Generated C#", Path.Combine(root, "Generated", "CSharp"), "Current", 1),
            new ProjectArtifactInspection("Generated Bytes", Path.Combine(root, "Generated", "Bytes"), "Pending source rows", 0),
            actions,
            [],
            InternalDirectory: Path.Combine(root, ".exceldb"));
    }

    private static void Inspect(ProjectHubForm form, string path)
    {
        var method = typeof(ProjectHubForm).GetMethod(
            "InspectCoreAsync",
            BindingFlags.Instance | BindingFlags.NonPublic)
            ?? throw new InvalidOperationException("ProjectHubForm.InspectCoreAsync was not found.");
        var task = (Task?)method.Invoke(form, [path, false, false])
            ?? throw new InvalidOperationException("ProjectHubForm.InspectCoreAsync returned no task.");
        var deadline = DateTime.UtcNow + TimeSpan.FromSeconds(10);
        while (!task.IsCompleted && DateTime.UtcNow < deadline)
        {
            Application.DoEvents();
            Thread.Sleep(1);
        }
        Assert.True(task.IsCompleted, "Project inspection timed out.");
        task.GetAwaiter().GetResult();
    }

    private static string? CurrentReportPath(ProjectHubForm form) =>
        (string?)PrivateField(form, "_currentReportPath");

    private static ProjectInspection? CurrentInspection(ProjectHubForm form) =>
        (ProjectInspection?)PrivateField(form, "_inspection");

    private static Button OpenReportButton(ProjectHubForm form) =>
        (Button)(PrivateField(form, "_openReport")
                 ?? throw new InvalidOperationException("ProjectHubForm._openReport was null."));

    private static Button PrivateButton(ProjectHubForm form, string fieldName) =>
        (Button)(PrivateField(form, fieldName)
                 ?? throw new InvalidOperationException($"ProjectHubForm.{fieldName} was null."));

    private static object? PrivateField(ProjectHubForm form, string name) =>
        (typeof(ProjectHubForm).GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)
         ?? throw new InvalidOperationException($"ProjectHubForm.{name} was not found."))
        .GetValue(form);

    private static string CreateTestRoot()
    {
        var root = Path.Combine(Path.GetTempPath(), "exceldb-project-hub-form-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return root;
    }

    private static void RunSta(Action action)
    {
        Exception? failure = null;
        var thread = new Thread(() =>
        {
            try
            {
                SynchronizationContext.SetSynchronizationContext(new WindowsFormsSynchronizationContext());
                action();
            }
            catch (Exception exception)
            {
                failure = exception;
            }
            finally
            {
                SynchronizationContext.SetSynchronizationContext(null);
            }
        });
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        Assert.True(thread.Join(TimeSpan.FromSeconds(15)), "STA form test timed out.");
        if (failure is not null)
            throw new AggregateException(failure);
    }

    private sealed class UnusedShell : IProjectHubShell
    {
        public void Open(string path) => throw new NotSupportedException();
    }

    private sealed class UnusedProjectService(
        Func<ProjectLocation, ProjectInspection>? inspect = null,
        Func<ProjectLocation, OperationReport>? repairAttributes = null) : IExcelDbProjectService
    {
        public ProjectInspection Inspect(ProjectLocation project) =>
            inspect?.Invoke(project) ?? throw new NotSupportedException();

        public OperationReport RepairProjectOwnedAttributes(ProjectLocation project) =>
            repairAttributes?.Invoke(project)
            ?? OperationReport.Success("project-repair-attributes", "test");

        public MutationPlan PlanInitialize(InitializeProjectRequest request) => throw new NotSupportedException();

        public MutationPlan PlanConfigure(ConfigureProjectRequest request) => throw new NotSupportedException();

        public Task<MutationPlan> PlanCreateTableAsync(CreateTableRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public Task<MutationPlan> PlanEditTableAsync(EditTableRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public Task<MutationPlan> PlanRegenerateAsync(RegenerateRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public Task<MutationPlan> PlanDataPrepareAsync(DataPrepareRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public MutationPlan PlanRepairSystemImports(RepairSystemImportsRequest request) => throw new NotSupportedException();

        public Task<OperationReport> CheckAsync(CheckRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public Task<OperationReport> ConvertAsync(ConvertRequest request, CancellationToken cancellationToken = default) => throw new NotSupportedException();

        public OperationReport CleanCache(ProjectLocation project) => throw new NotSupportedException();

        public OperationReport Apply(MutationPlan plan) => throw new NotSupportedException();
    }
}
