using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ExcelDb.Schema.Descriptors;

namespace ExcelDb.Schema.Generation;

public sealed record GeneratedSchemaArtifact(
    string RelativePath,
    string Kind,
    string? ExportTarget,
    string Content,
    string ContentHash);

public sealed record SchemaArtifactManifest(
    ulong SchemaHash,
    string CodegenHash,
    string Json,
    string ManifestHash,
    string? CatalogHash = null);

public sealed record SchemaCodeGenerationResult(
    ImmutableArray<GeneratedSchemaArtifact> Artifacts,
    SchemaArtifactManifest Manifest);

/// <summary>
/// Deterministically projects the canonical descriptor into full authoring C# and
/// isolated per-target runtime C#. It is deliberately pure: callers own atomic IO.
/// </summary>
public sealed class SchemaCodeGenerator
{
    public SchemaCodeGenerationResult Generate(CanonicalSchemaDescriptor descriptor) =>
        Generate(descriptor, catalogHash: null);

    /// <summary>
    /// Generates canonical artifacts and records the executable system-proto
    /// catalog identity in the ownership manifest when supplied.
    /// </summary>
    public SchemaCodeGenerationResult Generate(
        CanonicalSchemaDescriptor descriptor,
        string? catalogHash)
    {
        ArgumentNullException.ThrowIfNull(descriptor);
        if (catalogHash is not null && !IsSha256(catalogHash))
        {
            throw new ArgumentException(
                "Catalog hash must be a lower-case SHA-256 value.",
                nameof(catalogHash));
        }

        var allDefinitions = CollectDefinitions(descriptor, target: null);
        var allTypeNames = BuildTypeNames(descriptor, allDefinitions.Keys);
        var artifacts = ImmutableArray.CreateBuilder<GeneratedSchemaArtifact>();
        AddArtifact(
            artifacts,
            "Authoring/ExcelDbSchema.Authoring.g.cs",
            "authoring-csharp",
            null,
            GenerateSurface(descriptor, null, allDefinitions, allTypeNames));

        var targets = descriptor.Tables
            .SelectMany(static table => table.ExportTargets)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static value => value, StringComparer.Ordinal)
            .ToArray();
        foreach (var target in targets)
        {
            RequireSafeTargetId(target);
            var definitions = CollectDefinitions(descriptor, target);
            var safeTarget = SafeTargetIdentifier(target);
            var prefix = $"Runtime/{target}";
            AddArtifact(
                artifacts,
                $"{prefix}/ExcelDbSchema.Runtime.{safeTarget}.g.cs",
                "runtime-csharp",
                target,
                GenerateSurface(descriptor, target, definitions, allTypeNames));
            AddArtifact(
                artifacts,
                $"{prefix}/RuntimeSchemaRegistry.{safeTarget}.g.cs",
                "runtime-registry-csharp",
                target,
                GenerateRegistry(descriptor, target, safeTarget, allTypeNames));
        }

        var ordered = artifacts
            .OrderBy(static artifact => artifact.RelativePath, StringComparer.Ordinal)
            .ToImmutableArray();
        var codegenHash = ComputeCodegenHash(ordered);
        var manifestJson = BuildManifestJson(
            descriptor.SchemaHash,
            codegenHash,
            catalogHash,
            ordered);
        var manifestHash = Sha256(manifestJson);
        return new SchemaCodeGenerationResult(
            ordered,
            new SchemaArtifactManifest(
                descriptor.SchemaHash,
                codegenHash,
                manifestJson,
                manifestHash,
                catalogHash));
    }

    private static string GenerateSurface(
        CanonicalSchemaDescriptor descriptor,
        string? target,
        IReadOnlyDictionary<string, ShapeDefinition> definitions,
        IReadOnlyDictionary<string, string> typeNames)
    {
        var builder = new StringBuilder();
        var namespaceName = target is null
            ? "ExcelDb.Generated.Authoring"
            : $"ExcelDb.Generated.Runtime.{SafeTargetIdentifier(target)}";
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine("using System.Text.Json;");
        if (target is not null)
        {
            builder.AppendLine("using ExcelDb.Core.Identity;");
            builder.AppendLine("using ExcelDb.Runtime;");
        }
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine();
        AppendSupportContracts(builder, target is not null);

        var usedEnums = target is null
            ? descriptor.Enums.Select(static item => item.FullName).ToHashSet(StringComparer.Ordinal)
            : definitions.Values.SelectMany(static definition => definition.Fields.Values)
                .SelectMany(static field => field.Map?.KeyEnumType is { } keyEnum
                    ? new[] { field.TypeName, keyEnum }
                    : new[] { field.TypeName })
                .ToHashSet(StringComparer.Ordinal);
        foreach (var enumDescriptor in descriptor.Enums
                     .Where(item => usedEnums.Contains(item.FullName))
                     .OrderBy(static item => item.FullName, StringComparer.Ordinal))
            AppendEnum(builder, enumDescriptor, typeNames[enumDescriptor.FullName]);

        foreach (var definition in definitions.Values.OrderBy(static item => item.FullName, StringComparer.Ordinal))
        {
            AppendPoco(
                builder,
                definition,
                typeNames[definition.FullName],
                typeNames,
                target);
        }

        if (target is null)
            AppendSurfaceBindings(builder, descriptor, null, typeNames);
        else
            AppendRuntimeBindings(builder, descriptor, target, typeNames);
        builder.AppendLine("}");
        return NormalizeNewLines(builder.ToString());
    }

    private static void AppendSupportContracts(StringBuilder builder, bool runtime)
    {
        builder.AppendLine("[AttributeUsage(AttributeTargets.Class, Inherited = false)]");
        builder.AppendLine("public sealed class GeneratedTableAttribute : Attribute");
        builder.AppendLine("{");
        builder.AppendLine("    public GeneratedTableAttribute(int id, string fullName)");
        builder.AppendLine("    {");
        builder.AppendLine("        Id = id;");
        builder.AppendLine("        FullName = fullName;");
        builder.AppendLine("    }");
        builder.AppendLine("    public int Id { get; }");
        builder.AppendLine("    public string FullName { get; }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("[AttributeUsage(AttributeTargets.Property, Inherited = false)]");
        builder.AppendLine("public sealed class GeneratedFieldAttribute : Attribute");
        builder.AppendLine("{");
        builder.AppendLine("    public GeneratedFieldAttribute(int id, string fieldIdPath, string propertyPath)");
        builder.AppendLine("    {");
        builder.AppendLine("        Id = id;");
        builder.AppendLine("        FieldIdPath = fieldIdPath;");
        builder.AppendLine("        PropertyPath = propertyPath;");
        builder.AppendLine("    }");
        builder.AppendLine("    public int Id { get; }");
        builder.AppendLine("    public string FieldIdPath { get; }");
        builder.AppendLine("    public string PropertyPath { get; }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public enum GeneratedPhysicalFieldKind");
        builder.AppendLine("{");
        builder.AppendLine("    Cell = 0,");
        builder.AppendLine("    ExpandedColumn = 1,");
        builder.AppendLine("    RepeatedMessageChildTable = 2,");
        builder.AppendLine("    MessageMapChildTable = 3,");
        builder.AppendLine("    PropertyGroup = 4,");
        builder.AppendLine("}");
        builder.AppendLine("public sealed class GeneratedFieldBinding");
        builder.AppendLine("{");
        builder.AppendLine("    public GeneratedFieldBinding(int fieldId, int[] fieldIdPath, string propertyPath, string memberPath, string? displayName, string? headerComment, string[] aliases, GeneratedPhysicalFieldKind physicalKind, string? childSheet, string? parentGuidColumn, string? ordinalColumn, string? mapKeyColumn, Func<string, object?> parser, Func<object?, string> writer, string accessorId, string patcherId)");
        builder.AppendLine("    {");
        builder.AppendLine("        FieldId = fieldId;");
        builder.AppendLine("        FieldIdPath = Array.AsReadOnly(fieldIdPath);");
        builder.AppendLine("        PropertyPath = propertyPath;");
        builder.AppendLine("        MemberPath = memberPath;");
        builder.AppendLine("        DisplayName = displayName;");
        builder.AppendLine("        HeaderComment = headerComment;");
        builder.AppendLine("        Aliases = Array.AsReadOnly(aliases);");
        builder.AppendLine("        PhysicalKind = physicalKind;");
        builder.AppendLine("        ChildSheet = childSheet;");
        builder.AppendLine("        ParentGuidColumn = parentGuidColumn;");
        builder.AppendLine("        OrdinalColumn = ordinalColumn;");
        builder.AppendLine("        MapKeyColumn = mapKeyColumn;");
        builder.AppendLine("        Parser = parser;");
        builder.AppendLine("        Writer = writer;");
        builder.AppendLine("        AccessorId = accessorId;");
        builder.AppendLine("        PatcherId = patcherId;");
        builder.AppendLine("    }");
        builder.AppendLine("    public int FieldId { get; }");
        builder.AppendLine("    public IReadOnlyList<int> FieldIdPath { get; }");
        builder.AppendLine("    public string PropertyPath { get; }");
        builder.AppendLine("    public string MemberPath { get; }");
        builder.AppendLine("    public string? DisplayName { get; }");
        builder.AppendLine("    public string? HeaderComment { get; }");
        builder.AppendLine("    public IReadOnlyList<string> Aliases { get; }");
        builder.AppendLine("    public GeneratedPhysicalFieldKind PhysicalKind { get; }");
        builder.AppendLine("    public string? ChildSheet { get; }");
        builder.AppendLine("    public string? ParentGuidColumn { get; }");
        builder.AppendLine("    public string? OrdinalColumn { get; }");
        builder.AppendLine("    public string? MapKeyColumn { get; }");
        builder.AppendLine("    public Func<string, object?> Parser { get; }");
        builder.AppendLine("    public Func<object?, string> Writer { get; }");
        builder.AppendLine("    public string AccessorId { get; }");
        builder.AppendLine("    public string PatcherId { get; }");
        builder.AppendLine("}");
        if (!runtime)
        {
            builder.AppendLine("public sealed class GeneratedTableBinding");
            builder.AppendLine("{");
            builder.AppendLine("    public GeneratedTableBinding(int tableId, string fullName, string? displayName, Type clrType, string factoryId, string accessorId, string patcherId, IReadOnlyList<GeneratedFieldBinding> fields)");
            builder.AppendLine("    {");
            builder.AppendLine("        TableId = tableId;");
            builder.AppendLine("        FullName = fullName;");
            builder.AppendLine("        DisplayName = displayName;");
            builder.AppendLine("        ClrType = clrType;");
            builder.AppendLine("        FactoryId = factoryId;");
            builder.AppendLine("        AccessorId = accessorId;");
            builder.AppendLine("        PatcherId = patcherId;");
            builder.AppendLine("        Fields = fields;");
            builder.AppendLine("    }");
            builder.AppendLine("    public int TableId { get; }");
            builder.AppendLine("    public string FullName { get; }");
            builder.AppendLine("    public string? DisplayName { get; }");
            builder.AppendLine("    public Type ClrType { get; }");
            builder.AppendLine("    public string FactoryId { get; }");
            builder.AppendLine("    public string AccessorId { get; }");
            builder.AppendLine("    public string PatcherId { get; }");
            builder.AppendLine("    public IReadOnlyList<GeneratedFieldBinding> Fields { get; }");
            builder.AppendLine("}");
        }
        builder.AppendLine();
        builder.AppendLine("public readonly struct RowRef");
        builder.AppendLine("{");
        if (runtime)
        {
            builder.AppendLine("    public RowRef(AssetIdentity identity) { Identity = identity; }");
            builder.AppendLine("    public AssetIdentity Identity { get; }");
        }
        else
        {
            builder.AppendLine("    public RowRef(int table, Guid rowGuid) { Table = table; RowGuid = rowGuid; }");
            builder.AppendLine("    public int Table { get; }");
            builder.AppendLine("    public Guid RowGuid { get; }");
        }
        builder.AppendLine("}");
        builder.AppendLine("public readonly struct UnityResourceRef");
        builder.AppendLine("{");
        builder.AppendLine("    public UnityResourceRef(string guid, string mainAssetPath) { Guid = guid; MainAssetPath = mainAssetPath; }");
        builder.AppendLine("    public string Guid { get; }");
        builder.AppendLine("    public string MainAssetPath { get; }");
        builder.AppendLine("}");
        builder.AppendLine("public readonly struct LocalizedTextRef");
        builder.AppendLine("{");
        builder.AppendLine("    public LocalizedTextRef(string key) { Key = key; }");
        builder.AppendLine("    public string Key { get; }");
        builder.AppendLine("}");
        builder.AppendLine("public sealed class Curve { public List<CurvePoint> Points { get; set; } = new List<CurvePoint>(); }");
        builder.AppendLine("public sealed class CurvePoint");
        builder.AppendLine("{");
        builder.AppendLine("    public float X { get; set; }");
        builder.AppendLine("    public float Y { get; set; }");
        builder.AppendLine("    public float? InTangent { get; set; }");
        builder.AppendLine("    public float? OutTangent { get; set; }");
        builder.AppendLine("}");
        builder.AppendLine();

        if (!runtime)
        {
            builder.AppendLine("internal static class GeneratedCanonicalCellCodec");
            builder.AppendLine("{");
            builder.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions { PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower };");
            builder.AppendLine("    public static T Parse<T>(string text)");
            builder.AppendLine("    {");
            builder.AppendLine("        var declared = typeof(T);");
            builder.AppendLine("        var type = Nullable.GetUnderlyingType(declared) ?? declared;");
            builder.AppendLine("        if (text.Length == 0 && Nullable.GetUnderlyingType(declared) is not null) return default!;");
            builder.AppendLine("        object value;");
            builder.AppendLine("        if (type == typeof(string)) value = text;");
            builder.AppendLine("        else if (type == typeof(byte[])) value = Convert.FromBase64String(text);");
            builder.AppendLine("        else if (type == typeof(bool)) value = bool.Parse(text);");
            builder.AppendLine("        else if (type == typeof(int)) value = int.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type == typeof(uint)) value = uint.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type == typeof(long)) value = long.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type == typeof(ulong)) value = ulong.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type == typeof(float)) value = float.Parse(text, NumberStyles.Float, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type == typeof(double)) value = double.Parse(text, NumberStyles.Float, CultureInfo.InvariantCulture);");
            builder.AppendLine("        else if (type.IsEnum) value = int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? Enum.ToObject(type, number) : Enum.Parse(type, text, false);");
            builder.AppendLine("        else return JsonSerializer.Deserialize<T>(text, JsonOptions)!;");
            builder.AppendLine("        return (T)value;");
            builder.AppendLine("    }");
            builder.AppendLine("    public static string Write<T>(T value)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (value is null) return string.Empty;");
            builder.AppendLine("        if (value is string text) return text;");
            builder.AppendLine("        if (value is byte[] bytes) return Convert.ToBase64String(bytes);");
            builder.AppendLine("        if (value is IFormattable formattable) return formattable.ToString(null, CultureInfo.InvariantCulture) ?? string.Empty;");
            builder.AppendLine("        return JsonSerializer.Serialize(value, JsonOptions);");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static void AppendEnum(
        StringBuilder builder,
        CanonicalEnumDescriptor descriptor,
        string typeName)
    {
        builder.Append("public enum ").Append(typeName).AppendLine();
        builder.AppendLine("{");
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var value in descriptor.Values)
        {
            var name = UniqueIdentifier(ToPascalIdentifier(value.Name), value.Number, used);
            builder.Append("    ").Append(name).Append(" = ")
                .Append(value.Number.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendPoco(
        StringBuilder builder,
        ShapeDefinition definition,
        string typeName,
        IReadOnlyDictionary<string, string> typeNames,
        string? target)
    {
        if (definition.TableId is { } tableId)
        {
            builder.Append("[GeneratedTable(")
                .Append(tableId.ToString(CultureInfo.InvariantCulture)).Append(", ")
                .Append(CSharpString(definition.FullName)).AppendLine(")] ");
        }

        builder.Append("public sealed partial class ").Append(typeName).AppendLine();
        builder.AppendLine("{");
        var fields = definition.Fields.Values
            .Where(field => target is null || field.ExportTargets.Contains(target, StringComparer.Ordinal))
            .OrderBy(static field => field.Id)
            .ToArray();
        var memberNames = BuildMemberNames(fields);
        foreach (var group in fields
                     .Where(static field => field.OneOfGroup is not null)
                     .GroupBy(static field => field.OneOfGroup!, StringComparer.Ordinal)
                     .OrderBy(static group => group.Key, StringComparer.Ordinal))
        {
            builder.Append("    public int ")
                .Append(ToPascalIdentifier(group.Key)).AppendLine("VariantId { get; set; }");
        }

        foreach (var field in fields)
        {
            var memberName = memberNames[field.Id];
            builder.Append("    [GeneratedField(")
                .Append(field.Id.ToString(CultureInfo.InvariantCulture)).Append(", ")
                .Append(CSharpString(FormatFieldIdPath(field))).Append(", ")
                .Append(CSharpString(field.PropertyPath)).AppendLine(")] ");
            builder.Append("    public ").Append(GetCSharpType(field, typeNames))
                .Append(' ').Append(memberName).Append(" { get; set; }")
                .Append(GetInitializer(field, typeNames)).AppendLine();
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendSurfaceBindings(
        StringBuilder builder,
        CanonicalSchemaDescriptor descriptor,
        string? target,
        IReadOnlyDictionary<string, string> typeNames)
    {
        var tables = descriptor.Tables
            .Where(table => target is null || table.ExportTargets.Contains(target, StringComparer.Ordinal))
            .OrderBy(static table => table.Id)
            .ThenBy(static table => table.FullName, StringComparer.Ordinal)
            .ToArray();
        builder.AppendLine("public static class GeneratedSchemaBindings");
        builder.AppendLine("{");
        builder.AppendLine("    public static IReadOnlyList<GeneratedTableBinding> Tables { get; } = Array.AsReadOnly(new GeneratedTableBinding[]");
        builder.AppendLine("    {");
        foreach (var table in tables)
        {
            var fields = Flatten(table.Fields)
                .Where(field => target is null || field.ExportTargets.Contains(target, StringComparer.Ordinal))
                .OrderBy(static field => field.PropertyPath, StringComparer.Ordinal)
                .ThenBy(static field => field.Id)
                .ToArray();
            var topLevelMembers = BuildMemberNames(table.Fields);
            builder.Append("        new(")
                .Append(table.Id.ToString(CultureInfo.InvariantCulture)).Append(", ")
                .Append(CSharpString(table.FullName)).Append(", ")
                .Append(CSharpNullableString(table.DisplayName)).Append(", typeof(")
                .Append(typeNames[table.FullName]).Append("), ")
                .Append(CSharpString($"factory:{table.Id}")).Append(", ")
                .Append(CSharpString($"accessor:{table.Id}")).Append(", ")
                .Append(CSharpString($"patcher:{table.Id}")).AppendLine(", Array.AsReadOnly(new GeneratedFieldBinding[]");
            builder.AppendLine("        {");
            foreach (var field in fields)
            {
                var member = BuildMemberPath(field.PropertyPath, table.Fields, topLevelMembers);
                var codecName = CodecMethodName(table.Id, table.FullName, field);
                var fieldType = GetCSharpType(field, typeNames);
                var child = field.ChildTable;
                builder.Append("            new(")
                    .Append(field.Id.ToString(CultureInfo.InvariantCulture)).Append(", ")
                    .Append(IntArrayExpression(field.FieldIdPath)).Append(", ")
                    .Append(CSharpString(field.PropertyPath)).Append(", ")
                    .Append(CSharpString(member)).Append(", ")
                    .Append(CSharpNullableString(field.DisplayName)).Append(", ")
                    .Append(CSharpNullableString(field.HeaderComment)).Append(", ")
                    .Append(StringArrayExpression(field.Aliases)).Append(", ")
                    .Append(PhysicalKindExpression(field)).Append(", ")
                    .Append(CSharpNullableString(child?.SheetName)).Append(", ")
                    .Append(CSharpNullableString(child?.ParentGuidColumn)).Append(", ")
                    .Append(CSharpNullableString(child?.OrdinalColumn)).Append(", ")
                    .Append(CSharpNullableString(child?.MapKeyColumn)).Append(", ")
                    .Append("static text => GeneratedAuthoringCellCodecs.").Append(codecName)
                    .Append("_Parse(text), static value => GeneratedAuthoringCellCodecs.").Append(codecName)
                    .Append("_Write((").Append(fieldType).Append(")value!), ")
                    .Append(CSharpString($"accessor:{table.Id}:{field.PropertyPath}")).Append(", ")
                    .Append(CSharpString($"patcher:{table.Id}:{field.PropertyPath}")).AppendLine("),");
            }

            builder.AppendLine("        })),");
        }

        builder.AppendLine("    });");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedAuthoringCellCodecs");
        builder.AppendLine("{");
        foreach (var table in tables)
        {
            foreach (var field in Flatten(table.Fields)
                         .OrderBy(static field => string.Join(".", field.FieldIdPath), StringComparer.Ordinal))
            {
                var codecName = CodecMethodName(table.Id, table.FullName, field);
                var fieldType = GetCSharpType(field, typeNames);
                builder.Append("    public static ").Append(fieldType).Append(' ').Append(codecName)
                    .Append("_Parse(string text) => GeneratedCanonicalCellCodec.Parse<")
                    .Append(fieldType).AppendLine(">(text);");
                builder.Append("    public static string ").Append(codecName).Append("_Write(")
                    .Append(fieldType).Append(" value) => GeneratedCanonicalCellCodec.Write(value);")
                    .AppendLine();
            }
        }
        builder.AppendLine("}");
    }

    private static void AppendRuntimeBindings(
        StringBuilder builder,
        CanonicalSchemaDescriptor descriptor,
        string target,
        IReadOnlyDictionary<string, string> typeNames)
    {
        var tables = descriptor.Tables
            .Where(table => table.Kind == CanonicalTableKind.Asset
                && table.ExportTargets.Contains(target, StringComparer.Ordinal))
            .OrderBy(static table => table.Id)
            .ToArray();

        builder.AppendLine("internal static class RuntimeGeneratedValueCodec");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions { PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower };");
        builder.AppendLine("    public static T Parse<T>(ReadOnlySpan<byte> data)");
        builder.AppendLine("    {");
        builder.AppendLine("        var declared = typeof(T);");
        builder.AppendLine("        var type = Nullable.GetUnderlyingType(declared) ?? declared;");
        builder.AppendLine("        if (data.IsEmpty && Nullable.GetUnderlyingType(declared) is not null) return default!;");
        builder.AppendLine("        if (type == typeof(byte[])) return (T)(object)data.ToArray();");
        builder.AppendLine("        var text = Encoding.UTF8.GetString(data);");
        builder.AppendLine("        object value;");
        builder.AppendLine("        if (type == typeof(string)) value = text;");
        builder.AppendLine("        else if (type == typeof(bool)) value = bool.Parse(text);");
        builder.AppendLine("        else if (type == typeof(int)) value = int.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(uint)) value = uint.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(long)) value = long.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(ulong)) value = ulong.Parse(text, NumberStyles.Integer, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(float)) value = float.Parse(text, NumberStyles.Float, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(double)) value = double.Parse(text, NumberStyles.Float, CultureInfo.InvariantCulture);");
        builder.AppendLine("        else if (type == typeof(RowRef))");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!AssetIdentity.TryParse(text, out var identity)) throw new FormatException($\"Invalid RowRef '{text}'.\");");
        builder.AppendLine("            value = new RowRef(identity);");
        builder.AppendLine("        }");
        builder.AppendLine("        else if (type.IsEnum) value = int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var number) ? Enum.ToObject(type, number) : Enum.Parse(type, text, ignoreCase: false);");
        builder.AppendLine("        else return JsonSerializer.Deserialize<T>(data, JsonOptions)!;");
        builder.AppendLine("        return (T)value;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine("internal static class GeneratedRuntimeBindings");
        builder.AppendLine("{");
        builder.AppendLine("    public static IReadOnlyList<RuntimeTableBinding> Tables { get; } = Array.AsReadOnly(new RuntimeTableBinding[]");
        builder.AppendLine("    {");
        foreach (var table in tables)
        {
            var typeName = typeNames[table.FullName];
            builder.Append("        new RuntimeTableBinding<").Append(typeName).Append(">(")
                .Append(table.Id.ToString(CultureInfo.InvariantCulture)).Append(", static () => new ")
                .Append(typeName).Append("(), Apply_").Append(table.Id)
                .Append(", Reset_").Append(table.Id)
                .Append(", CreateRollback_").Append(table.Id)
                .Append(", CaptureRollback_").Append(table.Id)
                .Append(", Restore_").Append(table.Id).AppendLine("),");
        }

        builder.AppendLine("    });");
        builder.AppendLine();
        foreach (var table in tables)
        {
            var typeName = typeNames[table.FullName];
            var fields = table.Fields
                .Where(field => field.ExportTargets.Contains(target, StringComparer.Ordinal))
                .OrderBy(static field => field.Id)
                .ToArray();
            var runtimeFields = Flatten(table.Fields)
                .Where(field => field.ExportTargets.Contains(target, StringComparer.Ordinal))
                .OrderBy(static field => string.Join(".", field.FieldIdPath), StringComparer.Ordinal)
                .ToArray();
            var members = BuildMemberNames(table.Fields);
            builder.Append("    private static void Apply_").Append(table.Id).Append('(')
                .Append(typeName).AppendLine(" instance, RuntimeAssetRecord record)");
            builder.AppendLine("    {");
            builder.Append("        Reset_").Append(table.Id).AppendLine("(instance);");
            builder.AppendLine("        foreach (var field in record.Fields)");
            builder.AppendLine("        {");
            foreach (var field in runtimeFields)
                AppendRuntimeFieldAssignment(builder, table, field, typeNames);
            builder.AppendLine("        }");
            builder.AppendLine("    }");

            builder.Append("    private static void Reset_").Append(table.Id).Append('(')
                .Append(typeName).AppendLine(" instance)");
            builder.AppendLine("    {");
            foreach (var field in fields)
            {
                builder.Append("        instance.").Append(members[field.Id]).Append(" = ")
                    .Append(GetResetExpression(field)).AppendLine(";");
            }

            builder.AppendLine("    }");
            builder.Append("    private sealed class RollbackState_").Append(table.Id).AppendLine();
            builder.AppendLine("    {");
            for (var index = 0; index < fields.Length; index++)
            {
                builder.Append("        public ").Append(GetCSharpType(fields[index], typeNames))
                    .Append(" Value_").Append(index.ToString(CultureInfo.InvariantCulture))
                    .AppendLine(" = default!;");
            }

            builder.AppendLine("    }");
            builder.Append("    private static object CreateRollback_").Append(table.Id).Append('(')
                .Append(typeName).Append(" _) => new RollbackState_").Append(table.Id).AppendLine("();");
            builder.Append("    private static void CaptureRollback_").Append(table.Id).Append('(')
                .Append(typeName).AppendLine(" instance, object state)");
            builder.AppendLine("    {");
            builder.Append("        var values = (RollbackState_").Append(table.Id).AppendLine(")state;");
            for (var index = 0; index < fields.Length; index++)
            {
                var field = fields[index];
                builder.Append("        values.Value_").Append(index.ToString(CultureInfo.InvariantCulture))
                    .Append(" = instance.").Append(members[field.Id]).AppendLine(";");
            }

            builder.AppendLine("    }");
            builder.Append("    private static void Restore_").Append(table.Id).Append('(')
                .Append(typeName).AppendLine(" instance, object state)");
            builder.AppendLine("    {");
            builder.Append("        var values = (RollbackState_").Append(table.Id).AppendLine(")state;");
            for (var index = 0; index < fields.Length; index++)
            {
                var field = fields[index];
                builder.Append("        instance.").Append(members[field.Id]).Append(" = values.Value_")
                    .Append(index.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
    }

    private static string GetResetExpression(CanonicalFieldDescriptor field)
    {
        if (field.HasPresence)
            return "default!";
        if (field.Map is not null
            || field.Shape is CanonicalFieldShape.RepeatedScalar
                or CanonicalFieldShape.RepeatedEnum
                or CanonicalFieldShape.RepeatedMessage)
        {
            return "new()";
        }

        return field.TypeName switch
        {
            "string" => "string.Empty",
            "bytes" => "Array.Empty<byte>()",
            _ => "default!",
        };
    }

    private static string GenerateRegistry(
        CanonicalSchemaDescriptor descriptor,
        string target,
        string safeTarget,
        IReadOnlyDictionary<string, string> typeNames)
    {
        var builder = new StringBuilder();
        var namespaceName = $"ExcelDb.Generated.Runtime.{safeTarget}";
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using ExcelDb.Core.Identity;");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine();
        builder.AppendLine("public sealed class RuntimeSchemaRegistry : global::ExcelDb.Runtime.RuntimeSchemaRegistry");
        builder.AppendLine("{");
        builder.AppendLine("    public static RuntimeSchemaRegistry Instance { get; } = new RuntimeSchemaRegistry();");
        builder.Append("    private RuntimeSchemaRegistry() : base(0x")
            .Append(descriptor.SchemaHash.ToString("x16", CultureInfo.InvariantCulture))
            .Append("UL, new ExportTargetId(").Append(CSharpString(target))
            .AppendLine("), GeneratedRuntimeBindings.Tables) { }");
        builder.AppendLine("}");
        builder.AppendLine("}");
        _ = typeNames;
        return NormalizeNewLines(builder.ToString());
    }

    private static void AppendRuntimeFieldAssignment(
        StringBuilder builder,
        CanonicalTableDescriptor table,
        CanonicalFieldDescriptor field,
        IReadOnlyDictionary<string, string> typeNames)
    {
        var chain = ResolveFieldChain(table, field);
        var path = field.FieldIdPath.IsDefaultOrEmpty ? [field.Id] : field.FieldIdPath;
        builder.Append("            if (field.FieldIdPath.Length == ")
            .Append(path.Length.ToString(CultureInfo.InvariantCulture));
        for (var index = 0; index < path.Length; index++)
        {
            builder.Append(" && field.FieldIdPath[")
                .Append(index.ToString(CultureInfo.InvariantCulture))
                .Append("] == ")
                .Append(path[index].ToString(CultureInfo.InvariantCulture));
        }
        builder.AppendLine(")");
        builder.AppendLine("            {");

        var access = "instance";
        var siblings = table.Fields;
        for (var index = 0; index < chain.Length; index++)
        {
            var descriptor = chain[index];
            var member = BuildMemberNames(siblings)[descriptor.Id];
            access += "." + member;
            if (index < chain.Length - 1)
            {
                builder.Append("                if (").Append(access).Append(" is null) ")
                    .Append(access).Append(" = new ")
                    .Append(ResolveType(descriptor.TypeName, typeNames)).AppendLine("();");
            }
            siblings = descriptor.Children;
        }

        builder.Append("                ").Append(access)
            .Append(" = RuntimeGeneratedValueCodec.Parse<")
            .Append(GetCSharpType(field, typeNames)).AppendLine(">(field.Data.Span);");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
    }

    private static ImmutableArray<CanonicalFieldDescriptor> ResolveFieldChain(
        CanonicalTableDescriptor table,
        CanonicalFieldDescriptor leaf)
    {
        var path = leaf.FieldIdPath.IsDefaultOrEmpty ? [leaf.Id] : leaf.FieldIdPath;
        var result = ImmutableArray.CreateBuilder<CanonicalFieldDescriptor>(path.Length);
        var siblings = table.Fields;
        foreach (var fieldId in path)
        {
            var descriptor = siblings.FirstOrDefault(candidate => candidate.Id == fieldId)
                ?? throw new InvalidOperationException(
                    $"Field path '{string.Join('.', path)}' is not rooted in table '{table.FullName}'.");
            result.Add(descriptor);
            siblings = descriptor.Children;
        }
        return result.ToImmutable();
    }

    private static Dictionary<string, ShapeDefinition> CollectDefinitions(
        CanonicalSchemaDescriptor descriptor,
        string? target)
    {
        var result = new Dictionary<string, ShapeDefinition>(StringComparer.Ordinal);
        foreach (var table in descriptor.Tables
                     .Where(table => target is null || table.ExportTargets.Contains(target, StringComparer.Ordinal)))
        {
            AddDefinition(result, table.FullName, table.Id, table.Fields, target);
        }

        return result;
    }

    private static void AddDefinition(
        Dictionary<string, ShapeDefinition> result,
        string fullName,
        int? tableId,
        IEnumerable<CanonicalFieldDescriptor> fields,
        string? target)
    {
        if (!result.TryGetValue(fullName, out var definition))
        {
            definition = new ShapeDefinition(fullName, tableId);
            result.Add(fullName, definition);
        }

        foreach (var field in fields.OrderBy(static item => item.Id))
        {
            if (target is not null && !field.ExportTargets.Contains(target, StringComparer.Ordinal))
                continue;
            definition.Fields.TryAdd(field.Id, field);

            var messageType = field.Map?.ValueShape == CanonicalFieldShape.Message
                ? field.Map.ValueTypeName
                : field.Shape is CanonicalFieldShape.Message
                    or CanonicalFieldShape.RepeatedMessage
                    or CanonicalFieldShape.OneOfVariant
                    ? field.TypeName
                    : null;
            if (messageType is null || IsBuiltInType(messageType) || field.Children.IsEmpty)
                continue;
            AddDefinition(result, messageType, null, field.Children, target);
        }
    }

    private static IReadOnlyDictionary<string, string> BuildTypeNames(
        CanonicalSchemaDescriptor descriptor,
        IEnumerable<string> messageNames)
    {
        var fullNames = messageNames.Concat(descriptor.Enums.Select(static item => item.FullName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static value => value, StringComparer.Ordinal)
            .ToArray();
        var candidates = fullNames.ToDictionary(
            static fullName => fullName,
            static fullName => ToPascalIdentifier(fullName[(fullName.LastIndexOf('.') + 1)..]),
            StringComparer.Ordinal);
        var duplicateCandidates = candidates.Values
            .GroupBy(static value => value, StringComparer.Ordinal)
            .Where(static group => group.Count() > 1)
            .Select(static group => group.Key)
            .ToHashSet(StringComparer.Ordinal);
        return candidates.ToDictionary(
            static pair => pair.Key,
            pair => duplicateCandidates.Contains(pair.Value)
                ? $"{pair.Value}_{ShortHash(pair.Key)}"
                : pair.Value,
            StringComparer.Ordinal);
    }

    private static IReadOnlyDictionary<int, string> BuildMemberNames(
        IEnumerable<CanonicalFieldDescriptor> fields)
    {
        var ordered = fields.OrderBy(static field => field.Id).ToArray();
        var candidates = ordered.ToDictionary(
            static field => field.Id,
            static field => ToPascalIdentifier(field.Name));
        var duplicates = candidates.Values.GroupBy(static value => value, StringComparer.Ordinal)
            .Where(static group => group.Count() > 1)
            .Select(static group => group.Key)
            .ToHashSet(StringComparer.Ordinal);
        return candidates.ToDictionary(
            static pair => pair.Key,
            pair => duplicates.Contains(pair.Value) ? $"{pair.Value}_F{pair.Key}" : pair.Value);
    }

    private static string GetCSharpType(
        CanonicalFieldDescriptor field,
        IReadOnlyDictionary<string, string> typeNames)
    {
        string valueType;
        if (field.Map is { } map)
        {
            var keyType = map.KeyEnumType is not null
                ? ResolveType(map.KeyEnumType, typeNames)
                : ResolveType(map.KeyTypeName, typeNames);
            valueType = $"Dictionary<{keyType}, {ResolveType(map.ValueTypeName, typeNames)}>";
        }
        else
        {
            valueType = ResolveType(field.TypeName, typeNames);
            if (field.Shape is CanonicalFieldShape.RepeatedScalar
                or CanonicalFieldShape.RepeatedEnum
                or CanonicalFieldShape.RepeatedMessage)
            {
                valueType = $"List<{valueType}>";
            }
        }

        var nullable = field.Map is null
            && field.Shape is not (CanonicalFieldShape.RepeatedScalar
                or CanonicalFieldShape.RepeatedEnum
                or CanonicalFieldShape.RepeatedMessage)
            && field.HasPresence;
        return nullable ? $"{valueType}?" : valueType;
    }

    private static string GetInitializer(
        CanonicalFieldDescriptor field,
        IReadOnlyDictionary<string, string> typeNames)
    {
        if (field.HasPresence && field.Map is null)
            return string.Empty;
        if (field.Map is not null
            || field.Shape is CanonicalFieldShape.RepeatedScalar
                or CanonicalFieldShape.RepeatedEnum
                or CanonicalFieldShape.RepeatedMessage)
        {
            return " = new();";
        }

        return field.TypeName switch
        {
            "string" => " = string.Empty;",
            "bytes" => " = Array.Empty<byte>();",
            _ when field.Shape is CanonicalFieldShape.Message or CanonicalFieldShape.OneOfVariant => " = new();",
            _ => string.Empty,
        };
    }

    private static string ResolveType(string typeName, IReadOnlyDictionary<string, string> typeNames)
    {
        if (typeNames.TryGetValue(typeName, out var generated))
            return generated;
        return typeName switch
        {
            "double" => "double",
            "float" => "float",
            "int64" or "sint64" or "sfixed64" => "long",
            "uint64" or "fixed64" => "ulong",
            "int32" or "sint32" or "sfixed32" => "int",
            "uint32" or "fixed32" => "uint",
            "bool" => "bool",
            "string" => "string",
            "bytes" => "byte[]",
            "exceldb.RowRef" => "RowRef",
            "exceldb.UnityResourceRef" => "UnityResourceRef",
            "exceldb.LocalizedTextRef" => "LocalizedTextRef",
            "exceldb.Curve" => "Curve",
            "exceldb.CurvePoint" => "CurvePoint",
            _ => ToPascalIdentifier(typeName[(typeName.LastIndexOf('.') + 1)..]),
        };
    }

    private static bool IsValueTypeName(string typeName) => typeName is
        "double" or "float" or "int64" or "sint64" or "sfixed64"
        or "uint64" or "fixed64" or "int32" or "sint32" or "sfixed32"
        or "uint32" or "fixed32" or "bool"
        or "exceldb.RowRef" or "exceldb.UnityResourceRef" or "exceldb.LocalizedTextRef";

    private static bool IsBuiltInType(string typeName) => typeName.StartsWith("exceldb.", StringComparison.Ordinal);

    private static IEnumerable<CanonicalFieldDescriptor> Flatten(IEnumerable<CanonicalFieldDescriptor> fields)
    {
        foreach (var field in fields)
        {
            yield return field;
            foreach (var child in Flatten(field.Children))
                yield return child;
        }
    }

    private static void AddArtifact(
        ImmutableArray<GeneratedSchemaArtifact>.Builder artifacts,
        string path,
        string kind,
        string? target,
        string content)
    {
        var normalized = NormalizeNewLines(content);
        artifacts.Add(new GeneratedSchemaArtifact(path, kind, target, normalized, Sha256(normalized)));
    }

    private static string ComputeCodegenHash(ImmutableArray<GeneratedSchemaArtifact> artifacts)
    {
        var builder = new StringBuilder();
        foreach (var artifact in artifacts)
            builder.Append(artifact.RelativePath).Append('\0').Append(artifact.ContentHash).Append('\n');
        return Sha256(builder.ToString());
    }

    private static string BuildManifestJson(
        ulong schemaHash,
        string codegenHash,
        string? catalogHash,
        ImmutableArray<GeneratedSchemaArtifact> artifacts)
    {
        var builder = new StringBuilder();
        builder.Append("{\"format\":\"exceldb.codegen-manifest.v1\",\"schemaHash\":")
            .Append(JsonSerializer.Serialize(schemaHash.ToString("x16", CultureInfo.InvariantCulture)))
            .Append(",\"codegenHash\":").Append(JsonSerializer.Serialize(codegenHash));
        if (catalogHash is not null)
        {
            builder.Append(",\"catalogHash\":")
                .Append(JsonSerializer.Serialize(catalogHash));
        }

        builder.Append(",\"artifacts\":[");
        for (var index = 0; index < artifacts.Length; index++)
        {
            if (index != 0)
                builder.Append(',');
            var artifact = artifacts[index];
            builder.Append("{\"path\":").Append(JsonSerializer.Serialize(artifact.RelativePath))
                .Append(",\"kind\":").Append(JsonSerializer.Serialize(artifact.Kind))
                .Append(",\"exportTarget\":").Append(JsonSerializer.Serialize(artifact.ExportTarget))
                .Append(",\"sha256\":").Append(JsonSerializer.Serialize(artifact.ContentHash)).Append('}');
        }

        builder.Append("]}");
        return builder.ToString();
    }

    private static string Sha256(string value) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();

    private static bool IsSha256(string value) =>
        value.Length == 64
        && value.All(static character => character is >= '0' and <= '9' or >= 'a' and <= 'f');

    private static void RequireSafeTargetId(string target)
    {
        if (target.Length == 0
            || target[0] is < 'a' or > 'z'
            || target.Skip(1).Any(static character =>
                character is not (>= 'a' and <= 'z')
                && character is not (>= '0' and <= '9')
                && character != '-'))
        {
            throw new InvalidDataException(
                $"Export target cannot be used as a generated directory segment: '{target}'.");
        }
    }

    private static string ShortHash(string value) => Sha256(value)[..8];

    private static string SafeTargetIdentifier(string target) => $"Target_{ShortHash(target)}";

    private static string ToPascalIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length + 1);
        var upper = true;
        foreach (var character in value)
        {
            if (!char.IsAsciiLetterOrDigit(character) && character != '_')
            {
                upper = true;
                continue;
            }

            if (character == '_')
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        if (builder.Length == 0)
            builder.Append("Value");
        if (char.IsDigit(builder[0]))
            builder.Insert(0, '_');
        var result = builder.ToString();
        return CSharpKeywords.Contains(result) ? $"@{result}" : result;
    }

    private static string UniqueIdentifier(string candidate, int identity, HashSet<string> used)
    {
        if (used.Add(candidate))
            return candidate;
        var unique = $"{candidate}_{identity.ToString(CultureInfo.InvariantCulture).Replace('-', '_')}";
        used.Add(unique);
        return unique;
    }

    private static string CSharpString(string value) => JsonSerializer.Serialize(value);

    private static string CSharpNullableString(string? value) =>
        value is null ? "null" : CSharpString(value);

    private static string FormatFieldIdPath(CanonicalFieldDescriptor field) =>
        string.Join(".", field.FieldIdPath);

    private static string IntArrayExpression(IEnumerable<int> values) =>
        $"new int[] {{ {string.Join(", ", values.Select(static value => value.ToString(CultureInfo.InvariantCulture)))} }}";

    private static string StringArrayExpression(IEnumerable<string> values) =>
        $"new string[] {{ {string.Join(", ", values.Select(CSharpString))} }}";

    private static string CodecMethodName(
        int tableId,
        string tableFullName,
        CanonicalFieldDescriptor field) =>
        $"T{Math.Abs((long)tableId).ToString(CultureInfo.InvariantCulture)}_P{string.Join("_", field.FieldIdPath)}_{ShortHash(tableFullName)[..6]}";

    private static string PhysicalKindExpression(CanonicalFieldDescriptor field)
    {
        if (field.ChildTable?.Kind == CanonicalChildTableKind.RepeatedMessage)
            return "GeneratedPhysicalFieldKind.RepeatedMessageChildTable";
        if (field.ChildTable?.Kind == CanonicalChildTableKind.MessageMap)
            return "GeneratedPhysicalFieldKind.MessageMapChildTable";
        if (!field.Children.IsDefaultOrEmpty && field.ExpandMode == CanonicalExpandMode.ExpandedColumns)
            return "GeneratedPhysicalFieldKind.PropertyGroup";
        if (field.FieldIdPath.Length > 1)
            return "GeneratedPhysicalFieldKind.ExpandedColumn";
        return "GeneratedPhysicalFieldKind.Cell";
    }

    private static string BuildMemberPath(
        string propertyPath,
        ImmutableArray<CanonicalFieldDescriptor> topLevelFields,
        IReadOnlyDictionary<int, string> topLevelMembers)
    {
        var segments = propertyPath.Split('.');
        if (segments.Length == 0)
            return propertyPath;
        var top = topLevelFields.FirstOrDefault(field =>
            string.Equals(field.Name, segments[0], StringComparison.Ordinal));
        var first = top is not null && topLevelMembers.TryGetValue(top.Id, out var member)
            ? member
            : ToPascalIdentifier(segments[0]);
        if (segments.Length == 1)
            return first;
        return $"{first}.{string.Join(".", segments.Skip(1).Select(ToPascalIdentifier))}";
    }

    private static string NormalizeNewLines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while",
    };

    private sealed class ShapeDefinition(string fullName, int? tableId)
    {
        public string FullName { get; } = fullName;

        public int? TableId { get; } = tableId;

        public Dictionary<int, CanonicalFieldDescriptor> Fields { get; } = [];
    }
}
