using System.Collections.Immutable;
using ExcelDb.Core.Diagnostics;
using ExcelDb.Pipeline;
using ExcelDb.Tooling.Plans;

namespace ExcelDb.ProjectHub.Windows;

public sealed class ProjectHubForm : Form
{
    private readonly IExcelDbProjectService _service;
    private readonly LauncherStateStore _stateStore;
    private readonly IProjectHubShell _shell;
    private readonly ToolTip _toolTip = new();
    private readonly ListBox _recentProjects = new();
    private readonly TextBox _projectPath = new();
    private readonly Button _selectProject = new();
    private readonly Button _inspectProject = new();
    private readonly Button _removeRecent = new();
    private readonly Button _clearRecent = new();
    private readonly Label _availabilitySummary = new();
    private readonly Label _status = new();
    private readonly LinkLabel _reportLink = new();
    private readonly Panel _advancedPanel = new();
    private readonly LinkLabel _advancedToggle = new();
    private readonly List<Button> _operationButtons = [];
    private readonly List<Button> _advancedButtons = [];

    private readonly ArtifactCardControl _schemaCard;
    private readonly ArtifactCardControl _excelCard;
    private readonly ArtifactCardControl _generatedCSharpCard;
    private readonly ArtifactCardControl _generatedBytesCard;
    private Button _initialize = null!;
    private Button _createTable = null!;
    private Button _editTable = null!;
    private Button _regenerate = null!;
    private Button _prepareRows = null!;
    private Button _check = null!;
    private Button _convert = null!;
    private Button _repairImports = null!;
    private Button _configure = null!;
    private Button _openConfiguration = null!;
    private Button _openReport = null!;
    private Button _openInternal = null!;
    private Button _openRecovery = null!;
    private Button _cleanCache = null!;
    private ProjectInspection? _inspection;
    private string? _currentReportPath;
    private bool _busy;

    public ProjectHubForm(
        IExcelDbProjectService service,
        string initialDirectory,
        LauncherStateStore? stateStore = null,
        IProjectHubShell? shell = null)
    {
        _service = service ?? throw new ArgumentNullException(nameof(service));
        ArgumentNullException.ThrowIfNull(initialDirectory);
        _stateStore = stateStore ?? new LauncherStateStore();
        _shell = shell ?? new WindowsProjectHubShell();

        Text = "ExcelDB Project Hub";
        StartPosition = FormStartPosition.CenterScreen;
        MinimumSize = new Size(900, 720);
        Size = new Size(1060, 850);
        AutoScaleMode = AutoScaleMode.Dpi;

        _schemaCard = new ArtifactCardControl("Schema");
        _excelCard = new ArtifactCardControl("Excel");
        _generatedCSharpCard = new ArtifactCardControl("Generated C#");
        _generatedBytesCard = new ArtifactCardControl("Generated Bytes");
        foreach (var card in ArtifactCards)
            card.OpenRequested += (_, _) => OpenPath(card.ArtifactPath, $"打开 {card.ArtifactName}");

        Controls.Add(BuildLayout());
        LoadRecentProjects();

        if (!string.IsNullOrWhiteSpace(initialDirectory))
        {
            try
            {
                _projectPath.Text = Path.GetFullPath(initialDirectory);
            }
            catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException)
            {
                _status.Text = $"初始目录无效：{exception.Message}";
            }
        }

        Shown += InitialInspectAsync;
    }

    public IReadOnlyList<ArtifactCardControl> ArtifactCards =>
        [_schemaCard, _excelCard, _generatedCSharpCard, _generatedBytesCard];

    private Control BuildLayout()
    {
        var heading = new Label
        {
            AutoSize = true,
            Text = "选择一个目录，然后初始化或继续维护 ExcelDB 项目",
            Font = new Font(Font.FontFamily, 14, FontStyle.Bold),
            Margin = new Padding(0, 0, 0, 8),
        };

        _projectPath.Dock = DockStyle.Fill;
        _projectPath.PlaceholderText = "项目目录";
        _projectPath.KeyDown += async (_, eventArgs) =>
        {
            if (eventArgs.KeyCode != Keys.Enter)
                return;
            eventArgs.SuppressKeyPress = true;
            await InspectSelectedPathAsync(recordRecent: true);
        };
        _selectProject.Text = "选择项目目录…";
        _selectProject.AutoSize = true;
        _selectProject.Click += SelectProjectDirectoryAsync;
        _inspectProject.Text = "打开 / 检查";
        _inspectProject.AutoSize = true;
        _inspectProject.Click += async (_, _) => await InspectSelectedPathAsync(recordRecent: true);

        var pathRow = new TableLayoutPanel { Dock = DockStyle.Fill, AutoSize = true, ColumnCount = 3 };
        pathRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        pathRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pathRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        pathRow.Controls.Add(_projectPath, 0, 0);
        pathRow.Controls.Add(_selectProject, 1, 0);
        pathRow.Controls.Add(_inspectProject, 2, 0);

        _recentProjects.Dock = DockStyle.Fill;
        _recentProjects.Height = 72;
        _recentProjects.IntegralHeight = false;
        _recentProjects.DoubleClick += RecentProjectDoubleClickAsync;
        _recentProjects.SelectedIndexChanged += (_, _) => _removeRecent.Enabled = !_busy && _recentProjects.SelectedItem is RecentProjectItem;
        _removeRecent.Text = "移除所选";
        _removeRecent.AutoSize = true;
        _removeRecent.Enabled = false;
        _removeRecent.Click += RemoveRecentProject;
        _clearRecent.Text = "清空最近项目";
        _clearRecent.AutoSize = true;
        _clearRecent.Click += ClearRecentProjects;
        var recentButtons = new FlowLayoutPanel { AutoSize = true, Dock = DockStyle.Fill, FlowDirection = FlowDirection.TopDown, WrapContents = false };
        recentButtons.Controls.Add(_removeRecent);
        recentButtons.Controls.Add(_clearRecent);
        var recentRow = new TableLayoutPanel { Dock = DockStyle.Fill, Height = 80, ColumnCount = 2 };
        recentRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        recentRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        recentRow.Controls.Add(_recentProjects, 0, 0);
        recentRow.Controls.Add(recentButtons, 1, 0);

        var cards = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 2, RowCount = 2, MinimumSize = new Size(0, 310) };
        cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
        cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
        cards.RowStyles.Add(new RowStyle(SizeType.Percent, 50));
        cards.RowStyles.Add(new RowStyle(SizeType.Percent, 50));
        cards.Controls.Add(_schemaCard, 0, 0);
        cards.Controls.Add(_excelCard, 1, 0);
        cards.Controls.Add(_generatedCSharpCard, 0, 1);
        cards.Controls.Add(_generatedBytesCard, 1, 1);

        var actions = new FlowLayoutPanel { AutoSize = true, Dock = DockStyle.Fill, WrapContents = true };
        _initialize = AddAction(actions, "初始化项目", InitializeProjectAsync);
        _createTable = AddAction(actions, "创建表结构", CreateTableAsync);
        _editTable = AddAction(actions, "编辑表结构", EditTableAsync);
        _regenerate = AddAction(actions, "重新生成 C# 和 Excel", RegenerateAsync);
        _prepareRows = AddAction(actions, "准备新增行身份", PrepareRowsAsync);
        _check = AddAction(actions, "检查数据", CheckAsync);
        _convert = AddAction(actions, "按 target 生成 bytes", ConvertAsync);
        _repairImports = AddAction(actions, "修复 Proto 依赖", RepairImportsAsync);

        _availabilitySummary.AutoSize = true;
        _availabilitySummary.ForeColor = SystemColors.GrayText;
        _availabilitySummary.MaximumSize = new Size(900, 0);

        _advancedToggle.Text = "显示高级 / 诊断 ▸";
        _advancedToggle.AutoSize = true;
        _advancedToggle.LinkClicked += (_, _) =>
        {
            _advancedPanel.Visible = !_advancedPanel.Visible;
            _advancedToggle.Text = _advancedPanel.Visible ? "隐藏高级 / 诊断 ▾" : "显示高级 / 诊断 ▸";
        };
        _advancedPanel.Visible = false;
        _advancedPanel.AutoSize = true;
        _advancedPanel.Dock = DockStyle.Fill;
        var advancedActions = new FlowLayoutPanel { AutoSize = true, Dock = DockStyle.Fill, WrapContents = true };
        _configure = AddAdvancedAction(advancedActions, "项目设置", ConfigureProjectAsync);
        _openConfiguration = AddAdvancedAction(advancedActions, "打开项目配置", () => OpenPath(_inspection?.ProjectFilePath, "打开项目配置"));
        _openReport = AddAdvancedAction(advancedActions, "打开最新报告", () => OpenPath(_currentReportPath, "打开最新报告"));
        _openInternal = AddAdvancedAction(advancedActions, "打开内部目录", () => OpenPath(_inspection?.InternalDirectory, "打开内部目录"));
        _openRecovery = AddAdvancedAction(advancedActions, "打开恢复目录", () => OpenPath(_inspection?.RecoveryDirectory, "打开恢复目录"));
        _cleanCache = AddAdvancedAction(advancedActions, "清理缓存", CleanCacheAsync);
        _advancedPanel.Controls.Add(advancedActions);

        _status.AutoSize = true;
        _status.Text = "尚未选择项目。";
        _status.MaximumSize = new Size(820, 0);
        _reportLink.Text = "查看报告";
        _reportLink.AutoSize = true;
        _reportLink.Visible = false;
        _reportLink.LinkClicked += (_, _) => OpenPath(_currentReportPath, "查看报告");
        var statusRow = new FlowLayoutPanel { AutoSize = true, Dock = DockStyle.Fill, WrapContents = true, Padding = new Padding(0, 8, 0, 0) };
        statusRow.Controls.Add(_status);
        statusRow.Controls.Add(_reportLink);

        var layout = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            AutoScroll = true,
            Padding = new Padding(16),
            ColumnCount = 1,
            RowCount = 10,
        };
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 84));
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(heading, 0, 0);
        layout.Controls.Add(pathRow, 0, 1);
        layout.Controls.Add(recentRow, 0, 2);
        layout.Controls.Add(cards, 0, 3);
        layout.Controls.Add(actions, 0, 4);
        layout.Controls.Add(_availabilitySummary, 0, 5);
        layout.Controls.Add(_advancedToggle, 0, 6);
        layout.Controls.Add(_advancedPanel, 0, 7);
        layout.Controls.Add(statusRow, 0, 8);
        return layout;
    }

    private Button AddAction(Control parent, string text, Func<Task> action)
    {
        var button = new Button { Text = text, AutoSize = true, Enabled = false, Margin = new Padding(3, 5, 3, 5) };
        button.Click += async (_, _) => await action();
        parent.Controls.Add(button);
        _operationButtons.Add(button);
        return button;
    }

    private Button AddAdvancedAction(Control parent, string text, Action action)
    {
        var button = new Button { Text = text, AutoSize = true, Enabled = false };
        button.Click += (_, _) => action();
        parent.Controls.Add(button);
        _advancedButtons.Add(button);
        return button;
    }

    private Button AddAdvancedAction(Control parent, string text, Func<Task> action)
    {
        var button = new Button { Text = text, AutoSize = true, Enabled = false };
        button.Click += async (_, _) => await action();
        parent.Controls.Add(button);
        _advancedButtons.Add(button);
        return button;
    }

    private async void InitialInspectAsync(object? sender, EventArgs eventArgs)
    {
        if (!string.IsNullOrWhiteSpace(_projectPath.Text) && Directory.Exists(_projectPath.Text))
            await InspectSelectedPathAsync(recordRecent: true);
    }

    private async void SelectProjectDirectoryAsync(object? sender, EventArgs eventArgs)
    {
        using var picker = new FolderBrowserDialog
        {
            Description = "选择空目录或已有 ExcelDB 项目目录",
            UseDescriptionForTitle = true,
            ShowNewFolderButton = true,
            SelectedPath = Directory.Exists(_projectPath.Text) ? _projectPath.Text : string.Empty,
        };
        if (picker.ShowDialog(this) != DialogResult.OK)
            return;
        _projectPath.Text = picker.SelectedPath;
        await InspectSelectedPathAsync(recordRecent: true);
    }

    private async Task InspectSelectedPathAsync(bool recordRecent)
    {
        if (string.IsNullOrWhiteSpace(_projectPath.Text))
        {
            MessageBox.Show(this, "请先选择项目目录。", "ExcelDB", MessageBoxButtons.OK, MessageBoxIcon.Information);
            return;
        }
        await RunBusyAsync(() => InspectCoreAsync(_projectPath.Text, recordRecent, showInspectionStatus: true));
    }

    private async Task InspectCoreAsync(string path, bool recordRecent, bool showInspectionStatus)
    {
        var location = ProjectLocation.From(path);
        var requestedProjectRoot = ResolveProjectRoot(location.Path);
        var previousProjectRoot = _inspection?.ProjectRoot;
        if (previousProjectRoot is not null
            && !string.Equals(previousProjectRoot, requestedProjectRoot, StringComparison.OrdinalIgnoreCase))
        {
            _inspection = null;
            _currentReportPath = null;
            UpdateReportAvailability();
        }

        var inspection = await Task.Run(() => _service.Inspect(location));
        if (inspection.ProjectFilePath is not null
            && inspection.Status is not (ProjectStatus.Uninitialized
                or ProjectStatus.Legacy
                or ProjectStatus.Invalid
                or ProjectStatus.RecoveryRequired))
        {
            var attributeReport = await Task.Run(() => _service.RepairProjectOwnedAttributes(location));
            if (!attributeReport.Diagnostics.IsEmpty)
            {
                inspection = inspection with
                {
                    Diagnostics = inspection.Diagnostics
                        .AddRange(attributeReport.Diagnostics)
                        .Distinct()
                        .ToImmutableArray(),
                };
            }
        }
        if (previousProjectRoot is not null
            && !string.Equals(previousProjectRoot, inspection.ProjectRoot, StringComparison.OrdinalIgnoreCase))
        {
            _currentReportPath = null;
        }
        _inspection = inspection;
        _projectPath.Text = inspection.ProjectRoot;
        ApplyInspection(inspection);
        string? recentWarning = null;
        if (recordRecent)
        {
            try
            {
                _stateStore.RecordOpened(inspection.ProjectRoot);
                LoadRecentProjects();
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                recentWarning = $"最近项目记录未保存：{exception.Message}";
            }
        }
        if (showInspectionStatus)
        {
            var diagnostic = inspection.Diagnostics.FirstOrDefault(static item => item.IsFailure)
                ?? inspection.Diagnostics.FirstOrDefault();
            _status.Text = diagnostic is null
                ? $"项目状态：{inspection.Status}"
                : $"项目状态：{inspection.Status} — {diagnostic.Message}";
            if (recentWarning is not null)
                _status.Text += $"；{recentWarning}";
        }
    }

    private void ApplyInspection(ProjectInspection inspection, bool updateReportPath = true)
    {
        _schemaCard.UpdateInspection(inspection.Schema);
        _excelCard.UpdateInspection(inspection.Excel);
        _generatedCSharpCard.UpdateInspection(inspection.GeneratedCSharp);
        _generatedBytesCard.UpdateInspection(inspection.GeneratedBytes);

        SetAvailability(_initialize, inspection.Actions.Initialize);
        SetAvailability(_createTable, inspection.Actions.CreateTable);
        SetAvailability(_editTable, inspection.Actions.EditTable);
        SetAvailability(_regenerate, inspection.Actions.Regenerate);
        SetAvailability(_prepareRows, inspection.Actions.PrepareRows);
        SetAvailability(_check, inspection.Actions.Check);
        SetAvailability(_convert, inspection.Actions.Convert);
        SetAvailability(_repairImports, inspection.Actions.RepairSystemImports);
        SetAvailability(_configure, inspection.Actions.Configure);

        if (updateReportPath)
            _currentReportPath = ExistingPath(inspection.LatestReportPath);
        UpdateReportAvailability();
        _openConfiguration.Enabled = !_busy && ExistingPath(inspection.ProjectFilePath) is not null;
        _openInternal.Enabled = !_busy && ExistingPath(inspection.InternalDirectory) is not null;
        _openRecovery.Enabled = !_busy && ExistingPath(inspection.RecoveryDirectory) is not null;
        _cleanCache.Enabled = !_busy && inspection.InternalDirectory is not null;

        var disabled = new[]
        {
            ("初始化", inspection.Actions.Initialize),
            ("创建表", inspection.Actions.CreateTable),
            ("编辑表", inspection.Actions.EditTable),
            ("重新生成", inspection.Actions.Regenerate),
            ("准备行", inspection.Actions.PrepareRows),
            ("检查", inspection.Actions.Check),
            ("生成 bytes", inspection.Actions.Convert),
            ("修复 Proto", inspection.Actions.RepairSystemImports),
            ("设置", inspection.Actions.Configure),
        }.Where(static item => !item.Item2.Enabled && !string.IsNullOrWhiteSpace(item.Item2.DisabledReason))
            .Select(static item => $"{item.Item1}：{item.Item2.DisabledReason}")
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        _availabilitySummary.Text = disabled.Length == 0 ? string.Empty : string.Join("  |  ", disabled);
    }

    private void SetAvailability(Button button, ProjectActionAvailability availability)
    {
        button.Enabled = !_busy && availability.Enabled;
        var reason = availability.Enabled ? string.Empty : availability.DisabledReason ?? "当前项目状态不允许此操作。";
        button.AccessibleDescription = reason;
        _toolTip.SetToolTip(button, reason);
    }

    private async Task InitializeProjectAsync()
    {
        var projectRoot = _inspection?.ProjectRoot ?? _projectPath.Text;
        using var dialog = new InitializeProjectDialog(projectRoot);
        if (dialog.ShowDialog(this) != DialogResult.OK)
            return;
        await ExecutePlanAsync(() => Task.Run(() => _service.PlanInitialize(new InitializeProjectRequest(
            ProjectLocation.From(dialog.ProjectRoot),
            dialog.GeneratedCSharpDirectory))));
    }

    private async Task CreateTableAsync()
    {
        if (_inspection is null)
            return;
        var defaultWorkbook = ProjectArtifactPaths.GetDefaultWorkbookPath(
            _inspection.ProjectRoot,
            _inspection.Excel.Path);
        using var dialog = new CreateTableDialog(defaultWorkbook);
        if (dialog.ShowDialog(this) != DialogResult.OK)
            return;
        var request = new CreateTableRequest(ProjectLocation.From(_inspection.ProjectRoot), dialog.CreateIntent());
        await ExecutePlanAsync(() => _service.PlanCreateTableAsync(request));
    }

    private async Task EditTableAsync()
    {
        if (_inspection is null)
            return;
        using var dialog = new EditTableDialog();
        if (dialog.ShowDialog(this) != DialogResult.OK)
            return;
        var request = new EditTableRequest(ProjectLocation.From(_inspection.ProjectRoot), dialog.CreateIntent());
        await ExecutePlanAsync(() => _service.PlanEditTableAsync(request));
    }

    private async Task RegenerateAsync()
    {
        if (_inspection is null)
            return;
        var request = new RegenerateRequest(ProjectLocation.From(_inspection.ProjectRoot));
        await ExecutePlanAsync(() => _service.PlanRegenerateAsync(request));
    }

    private async Task PrepareRowsAsync()
    {
        if (_inspection is null)
            return;
        var request = new DataPrepareRequest(ProjectLocation.From(_inspection.ProjectRoot));
        await ExecutePlanAsync(() => _service.PlanDataPrepareAsync(request));
    }

    private async Task CheckAsync()
    {
        if (_inspection is null)
            return;
        await ExecuteReportOperationAsync(() => _service.CheckAsync(new CheckRequest(ProjectLocation.From(_inspection.ProjectRoot))));
    }

    private async Task ConvertAsync()
    {
        if (_inspection is null)
            return;
        using var dialog = new TargetDialog();
        if (dialog.ShowDialog(this) != DialogResult.OK)
            return;
        var request = new ConvertRequest(ProjectLocation.From(_inspection.ProjectRoot), dialog.Target);
        await ExecuteReportOperationAsync(() => _service.ConvertAsync(request));
    }

    private async Task RepairImportsAsync()
    {
        if (_inspection is null)
            return;
        var request = new RepairSystemImportsRequest(ProjectLocation.From(_inspection.ProjectRoot));
        await ExecutePlanAsync(() => Task.Run(() => _service.PlanRepairSystemImports(request)));
    }

    private async Task ConfigureProjectAsync()
    {
        if (_inspection is null)
            return;
        using var dialog = new ProjectSettingsDialog(_inspection);
        if (dialog.ShowDialog(this) != DialogResult.OK)
            return;
        var request = new ConfigureProjectRequest(
            ProjectLocation.From(_inspection.ProjectRoot),
            dialog.SchemaDirectory,
            dialog.ExcelDirectory,
            dialog.GeneratedCSharpDirectory,
            dialog.GeneratedBytesDirectory);
        await ExecutePlanAsync(() => Task.Run(() => _service.PlanConfigure(request)));
    }

    private async Task CleanCacheAsync()
    {
        if (_inspection is null)
            return;
        if (MessageBox.Show(
                this,
                "只清理可删除的 .exceldb/cache；配置、发布历史、报告和恢复日志不会被删除。继续吗？",
                "清理 ExcelDB 缓存",
                MessageBoxButtons.OKCancel,
                MessageBoxIcon.Question) != DialogResult.OK)
        {
            return;
        }
        var location = ProjectLocation.From(_inspection.ProjectRoot);
        await ExecuteReportOperationAsync(() => Task.Run(() => _service.CleanCache(location)));
    }

    private async Task ExecutePlanAsync(Func<Task<MutationPlan>> createPlan)
    {
        await RunBusyAsync(async () =>
        {
            _status.Text = "正在构造不可变操作计划…";
            var plan = await createPlan();
            if (!PlanPreviewDialog.Confirm(this, plan))
            {
                _status.Text = "已取消；项目工件没有写入。";
                return;
            }
            _status.Text = "正在应用已确认的计划…";
            var report = await Task.Run(() => _service.Apply(plan));
            await RefreshAfterReportAsync(report);
        });
    }

    private async Task ExecuteReportOperationAsync(Func<Task<OperationReport>> operation)
    {
        await RunBusyAsync(async () =>
        {
            _status.Text = "正在执行…";
            var report = await operation();
            await RefreshAfterReportAsync(report);
        });
    }

    private async Task RefreshAfterReportAsync(OperationReport report)
    {
        var reportArtifact = report.Artifacts.FirstOrDefault(static item =>
            item.Kind.Contains("report", StringComparison.OrdinalIgnoreCase));
        var operationReportPath = reportArtifact is null ? null : ExistingPath(reportArtifact.Path);
        _currentReportPath = operationReportPath;
        UpdateReportAvailability();

        if (_inspection is not null)
        {
            try
            {
                await InspectCoreAsync(_inspection.ProjectRoot, recordRecent: false, showInspectionStatus: false);
            }
            catch (Exception exception)
            {
                PresentException("操作完成，但刷新项目状态失败", exception);
                return;
            }
        }

        _currentReportPath = operationReportPath ?? ExistingPath(_inspection?.LatestReportPath);
        var diagnostic = report.Diagnostics.FirstOrDefault(static item => item.IsFailure)
            ?? report.Diagnostics.FirstOrDefault();
        _status.Text = report.Succeeded
            ? report.Applied ? $"{report.Operation} 已应用。" : $"{report.Operation} 已完成，无需修改领域工件。"
            : $"{report.Operation} 失败；{diagnostic?.Message ?? "原有领域工件已保留。"}";
        UpdateReportAvailability();
    }

    private async Task RunBusyAsync(Func<Task> action)
    {
        if (_busy)
            return;
        SetBusy(true);
        try
        {
            await action();
        }
        catch (Exception exception)
        {
            PresentException("ExcelDB 操作失败", exception);
        }
        finally
        {
            SetBusy(false);
        }
    }

    private void SetBusy(bool busy)
    {
        _busy = busy;
        UseWaitCursor = busy;
        _projectPath.Enabled = !busy;
        _selectProject.Enabled = !busy;
        _inspectProject.Enabled = !busy;
        _recentProjects.Enabled = !busy;
        _clearRecent.Enabled = !busy;
        _removeRecent.Enabled = !busy && _recentProjects.SelectedItem is RecentProjectItem;
        if (_inspection is null)
        {
            foreach (var button in _operationButtons.Concat(_advancedButtons))
                button.Enabled = false;
        }
        else
        {
            ApplyInspection(_inspection, updateReportPath: false);
        }
    }

    private void PresentException(string heading, Exception exception)
    {
        _status.Text = $"{heading}：{exception.Message}";
        if (_currentReportPath is null && _inspection?.LatestReportPath is { } latest)
            _currentReportPath = ExistingPath(latest);
        UpdateReportAvailability();
        MessageBox.Show(this, exception.Message, heading, MessageBoxButtons.OK, MessageBoxIcon.Error);
    }

    private void UpdateReportAvailability()
    {
        _reportLink.Visible = _currentReportPath is not null;
        _openReport.Enabled = !_busy && _currentReportPath is not null;
    }

    private void OpenPath(string? path, string title)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            MessageBox.Show(this, "当前没有可打开的路径。", title, MessageBoxButtons.OK, MessageBoxIcon.Information);
            return;
        }
        try
        {
            _shell.Open(path);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or InvalidOperationException)
        {
            MessageBox.Show(this, exception.Message, title, MessageBoxButtons.OK, MessageBoxIcon.Warning);
        }
    }

    private void LoadRecentProjects()
    {
        var selectedPath = (_recentProjects.SelectedItem as RecentProjectItem)?.Project.Path;
        _recentProjects.BeginUpdate();
        try
        {
            _recentProjects.Items.Clear();
            foreach (var project in _stateStore.Load().RecentProjects)
                _recentProjects.Items.Add(new RecentProjectItem(project, Directory.Exists(project.Path)));
            if (selectedPath is not null)
            {
                var selected = _recentProjects.Items.Cast<RecentProjectItem>()
                    .FirstOrDefault(item => string.Equals(item.Project.Path, selectedPath, StringComparison.OrdinalIgnoreCase));
                if (selected is not null)
                    _recentProjects.SelectedItem = selected;
            }
        }
        finally
        {
            _recentProjects.EndUpdate();
        }
        _clearRecent.Enabled = !_busy && _recentProjects.Items.Count != 0;
    }

    private async void RecentProjectDoubleClickAsync(object? sender, EventArgs eventArgs)
    {
        if (_recentProjects.SelectedItem is not RecentProjectItem item)
            return;
        if (!item.Exists)
        {
            MessageBox.Show(this, "该最近项目目录已经不存在；可选择“移除所选”。", "最近项目", MessageBoxButtons.OK, MessageBoxIcon.Information);
            return;
        }
        _projectPath.Text = item.Project.Path;
        await InspectSelectedPathAsync(recordRecent: true);
    }

    private void RemoveRecentProject(object? sender, EventArgs eventArgs)
    {
        if (_recentProjects.SelectedItem is not RecentProjectItem item)
            return;
        try
        {
            _stateStore.Remove(item.Project.Path);
            LoadRecentProjects();
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            PresentException("无法移除最近项目", exception);
        }
    }

    private void ClearRecentProjects(object? sender, EventArgs eventArgs)
    {
        if (_recentProjects.Items.Count == 0)
            return;
        if (MessageBox.Show(this, "清空最近项目导航记录？这不会修改任何项目。", "最近项目", MessageBoxButtons.OKCancel, MessageBoxIcon.Question) != DialogResult.OK)
            return;
        try
        {
            _stateStore.Clear();
            LoadRecentProjects();
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            PresentException("无法清空最近项目", exception);
        }
    }

    private static string? ExistingPath(string? path) =>
        !string.IsNullOrWhiteSpace(path) && (File.Exists(path) || Directory.Exists(path)) ? path : null;

    private static string ResolveProjectRoot(string path)
    {
        var full = Path.GetFullPath(path);
        if (string.Equals(Path.GetFileName(full), "project.json", StringComparison.OrdinalIgnoreCase)
            && string.Equals(Path.GetFileName(Path.GetDirectoryName(full)), ".exceldb", StringComparison.OrdinalIgnoreCase))
        {
            return Path.GetDirectoryName(Path.GetDirectoryName(full)!)!;
        }
        return File.Exists(full)
            ? Path.GetDirectoryName(full) ?? full
            : full;
    }

    private sealed record RecentProjectItem(RecentProject Project, bool Exists)
    {
        public override string ToString()
        {
            var name = Path.GetFileName(Project.Path);
            if (string.IsNullOrWhiteSpace(name))
                name = Project.Path;
            return $"{(Exists ? string.Empty : "[不存在] ")}{name} — {Project.Path}";
        }
    }
}
