using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ExcelDb.Pipeline;
using ExcelDb.Schema.Authoring;
using ExcelDb.Schema.Compilation;
using ExcelDb.Tooling.Plans;
using ExcelDb.Tooling.Project;
using ExcelDb.Workbooks.Model;
using ExcelDb.Workbooks.OpenXml;

namespace ExcelDb.Pipeline.Tests;

public sealed class ExcelDbProjectServiceTests : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(),
        "exceldb-project-service-tests",
        Guid.NewGuid().ToString("N"));

    private readonly string _externalCSharp = Path.Combine(
        Path.GetTempPath(),
        "exceldb-project-service-external",
        Guid.NewGuid().ToString("N"));

    [Fact]
    public void Initialize_is_one_v2_plan_for_four_artifacts_and_the_complete_owned_system_mirror()
    {
        var catalog = PackageSystemProtoCatalog.Default;
        var service = CreateService(catalog: catalog);

        var plan = service.PlanInitialize(new InitializeProjectRequest(Location));

        Assert.Equal(MutationPlan.CurrentFormatVersion, plan.FormatVersion);
        Assert.False(plan.HasBlockers, FormatDiagnostics(plan));
        Assert.Equal(catalog.CatalogHash, plan.SystemCatalogHash);
        Assert.Contains(plan.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == ".exceldb/project.json");
        Assert.Contains(plan.Mutations, mutation =>
            mutation.Root == PlanRootKind.GeneratedCSharp
            && mutation.Kind == FileMutationKind.CreateDirectory);

        Apply(service, plan);

        Assert.True(Directory.Exists(Path.Combine(_root, "Schema")));
        Assert.True(Directory.Exists(Path.Combine(_root, "Excel")));
        Assert.True(Directory.Exists(Path.Combine(_root, "Generated", "CSharp")));
        Assert.True(Directory.Exists(Path.Combine(_root, "Generated", "Bytes")));
        Assert.False(Directory.Exists(Path.Combine(_root, "Data")));
        Assert.False(Directory.Exists(Path.Combine(_root, "Import")));
        Assert.False(Directory.Exists(Path.Combine(_root, "Build")));
        Assert.False(Directory.Exists(Path.Combine(_root, "Config")));

        Assert.True(catalog.Files.Count >= 12);
        Assert.True(catalog.Files.Count(file => file.LogicalPath.StartsWith("google/protobuf/", StringComparison.Ordinal)) >= 11);
        foreach (var file in catalog.Files)
        {
            var mirror = Path.Combine(
                _root,
                "Schema",
                file.LogicalPath.Replace('/', Path.DirectorySeparatorChar));
            Assert.True(File.Exists(mirror), file.LogicalPath);
            Assert.Equal(file.CanonicalBytes.ToArray(), File.ReadAllBytes(mirror));
        }

        var manifestPath = Path.Combine(_root, ".exceldb", "system-imports.json");
        using var manifest = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        Assert.Equal(catalog.CatalogHash, manifest.RootElement.GetProperty("catalogHash").GetString());
        Assert.Equal(catalog.Files.Count, manifest.RootElement.GetProperty("files").GetArrayLength());

        var sourceSet = SchemaSourceSet.Discover(Path.Combine(_root, "Schema"), catalog);
        Assert.Empty(sourceSet.Files);
    }

    [Fact]
    public void Inspect_projects_exactly_the_four_user_artifact_cards()
    {
        var service = CreateService();
        Initialize(service);

        var inspection = service.Inspect(Location);
        var cards = new[]
        {
            inspection.Schema,
            inspection.Excel,
            inspection.GeneratedCSharp,
            inspection.GeneratedBytes,
        };

        Assert.Equal(new[] { "Schema", "Excel", "Generated C#", "Generated Bytes" }, cards.Select(static card => card.Name));
        Assert.Equal(Path.Combine(_root, "Schema"), inspection.Schema.Path);
        Assert.Equal(Path.Combine(_root, "Excel"), inspection.Excel.Path);
        Assert.Equal(Path.Combine(_root, "Generated", "CSharp"), inspection.GeneratedCSharp.Path);
        Assert.Equal(Path.Combine(_root, "Generated", "Bytes"), inspection.GeneratedBytes.Path);
        Assert.Equal(Path.Combine(_root, ".exceldb"), inspection.InternalDirectory);
        Assert.Equal(ProjectStatus.NoTables, inspection.Status);
    }

    [Fact]
    public void Inspect_is_read_only_and_counts_compiled_tables_instead_of_proto_files()
    {
        var service = CreateService();
        Initialize(service);
        File.WriteAllText(
            Path.Combine(_root, "Schema", "Helper.proto"),
            """
            syntax = "proto3";
            package helper;
            import "exceldb/options.proto";
            message Helper {
              option (exceldb.table) = { kind: EMBEDDED };
              string value = 1;
            }
            """,
            new UTF8Encoding(false));
        var internalDirectory = Path.Combine(_root, ".exceldb");
        var optionsPath = Path.Combine(_root, "Schema", "exceldb", "options.proto");
        File.SetAttributes(internalDirectory, File.GetAttributes(internalDirectory) & ~FileAttributes.Hidden);
        File.SetAttributes(optionsPath, File.GetAttributes(optionsPath) & ~FileAttributes.ReadOnly);
        Directory.CreateDirectory(Path.Combine(internalDirectory, "cache", "inspect-sentinel"));
        File.WriteAllText(
            Path.Combine(internalDirectory, "cache", "inspect-sentinel", "keep.txt"),
            "keep",
            new UTF8Encoding(false));
        var before = SnapshotTree(_root);

        var first = service.Inspect(Location);
        var second = service.Inspect(Location);

        Assert.Equal(ProjectStatus.NoTables, first.Status);
        Assert.Equal(0, first.Schema.ItemCount);
        Assert.Equal("No tables", first.Schema.Status);
        Assert.Equal(first.Status, second.Status);
        Assert.Equal(first.Diagnostics.ToArray(), second.Diagnostics.ToArray());
        AssertTreeUnchanged(before, SnapshotTree(_root));
        Assert.Equal((FileAttributes)0, File.GetAttributes(internalDirectory) & FileAttributes.Hidden);
        Assert.Equal((FileAttributes)0, File.GetAttributes(optionsPath) & FileAttributes.ReadOnly);
    }

    [Fact]
    public void Dual_configuration_is_legacy_before_recovery_and_inspection_writes_nothing()
    {
        var service = CreateService();
        Initialize(service);
        File.WriteAllText(
            Path.Combine(_root, ExcelDbProject.LegacyFileName),
            "{}\n",
            new UTF8Encoding(false));
        var recoverySentinel = Path.Combine(_root, ".exceldb", "recovery", "must-remain");
        File.WriteAllText(recoverySentinel, "pending", new UTF8Encoding(false));
        var before = SnapshotTree(_root);

        var inspection = service.Inspect(Location);

        Assert.Equal(ProjectStatus.Legacy, inspection.Status);
        Assert.Contains(inspection.Diagnostics, diagnostic => diagnostic.Code == "project.legacy-v1");
        Assert.False(inspection.Actions.Initialize.Enabled);
        Assert.True(File.Exists(recoverySentinel));
        AssertTreeUnchanged(before, SnapshotTree(_root));
        Assert.Throws<InvalidDataException>(() => service.CleanCache(Location));
        AssertTreeUnchanged(before, SnapshotTree(_root));
    }

    [Fact]
    public void Inspect_and_clean_cache_block_project_and_internal_junctions_without_outside_changes()
    {
        var service = CreateService();
        var container = Path.Combine(
            Path.GetTempPath(),
            "exceldb-project-service-reparse-tests",
            Guid.NewGuid().ToString("N"));
        var outsideProject = Path.Combine(container, "outside-project");
        var projectAlias = Path.Combine(container, "project-alias");
        var plainProject = Path.Combine(container, "plain-project");
        var outsideInternal = Path.Combine(container, "outside-internal");
        var internalLink = Path.Combine(plainProject, ".exceldb");
        Directory.CreateDirectory(outsideProject);
        Directory.CreateDirectory(plainProject);
        Directory.CreateDirectory(outsideInternal);
        File.WriteAllText(Path.Combine(outsideProject, "sentinel.txt"), "keep", new UTF8Encoding(false));
        File.WriteAllText(Path.Combine(outsideInternal, "sentinel.txt"), "keep", new UTF8Encoding(false));
        try
        {
            if (!TryCreateDirectoryLink(projectAlias, outsideProject))
                return;
            var projectBefore = SnapshotTree(outsideProject);

            var aliased = service.Inspect(ProjectLocation.From(projectAlias));

            Assert.Equal(ProjectStatus.Invalid, aliased.Status);
            Assert.Contains(aliased.Diagnostics, diagnostic => diagnostic.Code == "project.path-unsafe");
            Assert.Throws<InvalidDataException>(() => service.CleanCache(ProjectLocation.From(projectAlias)));
            Assert.Equal(projectBefore, SnapshotTree(outsideProject));
            DeleteLinkIfPresent(projectAlias);

            if (!TryCreateDirectoryLink(internalLink, outsideInternal))
                return;
            var internalBefore = SnapshotTree(outsideInternal);

            var linkedInternal = service.Inspect(ProjectLocation.From(plainProject));

            Assert.Equal(ProjectStatus.Invalid, linkedInternal.Status);
            Assert.Contains(linkedInternal.Diagnostics, diagnostic => diagnostic.Code == "project.path-unsafe");
            Assert.Throws<InvalidDataException>(() => service.CleanCache(ProjectLocation.From(plainProject)));
            Assert.Equal(internalBefore, SnapshotTree(outsideInternal));
        }
        finally
        {
            DeleteLinkIfPresent(projectAlias);
            DeleteLinkIfPresent(internalLink);
            DeleteTree(container);
        }
    }

    [Fact]
    public async Task Inspect_maps_codegen_pending_and_exact_bytes_facts_to_cards_and_actions()
    {
        var service = CreateService();
        Initialize(service);
        await CreateHeroAsync(service);

        var missingBytes = service.Inspect(Location);
        Assert.Equal(ProjectStatus.BytesGenerationRequired, missingBytes.Status);
        Assert.Equal(1, missingBytes.Schema.ItemCount);
        Assert.DoesNotContain("Regeneration required", missingBytes.GeneratedCSharp.Status, StringComparison.Ordinal);
        Assert.Equal(2, missingBytes.GeneratedByteTargets.Length);
        Assert.All(missingBytes.GeneratedByteTargets, target =>
            Assert.Equal(ProjectTargetArtifactStatus.Missing, target.Status));
        Assert.True(missingBytes.Actions.Convert.Enabled);

        var generatedPath = Path.Combine(
            _root,
            "Generated",
            "CSharp",
            "Authoring",
            "ExcelDbSchema.Authoring.g.cs");
        var generatedBefore = File.ReadAllBytes(generatedPath);
        File.AppendAllText(generatedPath, "// modified\n", new UTF8Encoding(false));
        var staleCodegen = service.Inspect(Location);
        Assert.Equal(ProjectStatus.RegenerationRequired, staleCodegen.Status);
        Assert.Contains("Regeneration required", staleCodegen.GeneratedCSharp.Status, StringComparison.Ordinal);
        Assert.True(staleCodegen.Actions.Regenerate.Enabled);
        Assert.False(staleCodegen.Actions.Convert.Enabled);

        File.WriteAllBytes(generatedPath, generatedBefore);
        var workbookPath = Path.Combine(_root, "Excel", "game.xlsx");
        AddPendingRow(workbookPath, "hero-1", "First");
        var pending = service.Inspect(Location);
        Assert.Equal(ProjectStatus.PendingRows, pending.Status);
        Assert.Equal(1, pending.PendingIdentityCount);
        Assert.True(pending.Actions.PrepareRows.Enabled);
        Assert.False(pending.Actions.Convert.Enabled);
        Assert.Contains("pending row", pending.Actions.Convert.DisabledReason!, StringComparison.OrdinalIgnoreCase);

        Apply(service, await service.PlanDataPrepareAsync(new DataPrepareRequest(Location)));
        var prepared = service.Inspect(Location);
        Assert.Equal(ProjectStatus.BytesGenerationRequired, prepared.Status);
        Assert.Equal(0, prepared.PendingIdentityCount);
        Assert.True(prepared.Actions.Convert.Enabled);

        var client = await service.ConvertAsync(new ConvertRequest(Location, "client"));
        var server = await service.ConvertAsync(new ConvertRequest(Location, "server"));
        Assert.True(client.Succeeded, FormatDiagnostics(client));
        Assert.True(server.Succeeded, FormatDiagnostics(server));
        var ready = service.Inspect(Location);
        Assert.Equal(ProjectStatus.Ready, ready.Status);
        Assert.All(ready.GeneratedByteTargets, target =>
            Assert.Equal(ProjectTargetArtifactStatus.Current, target.Status));

        ReplaceBusinessCell(workbookPath, "name", "Changed after convert");
        var staleBytes = service.Inspect(Location);
        Assert.Equal(ProjectStatus.BytesGenerationRequired, staleBytes.Status);
        Assert.Contains("Generate bytes", staleBytes.GeneratedBytes.Status, StringComparison.Ordinal);
        Assert.All(staleBytes.GeneratedByteTargets, target =>
            Assert.Equal(ProjectTargetArtifactStatus.Stale, target.Status));
        Assert.True(staleBytes.Actions.Convert.Enabled);

        File.WriteAllBytes(
            Path.Combine(_root, "Generated", "Bytes", "client", "config.bytes"),
            [1, 2, 3]);
        var corruptBytes = service.Inspect(Location);
        Assert.Equal(ProjectStatus.BytesGenerationRequired, corruptBytes.Status);
        Assert.Equal(
            ProjectTargetArtifactStatus.Corrupt,
            Assert.Single(corruptBytes.GeneratedByteTargets, target => target.Target == "client").Status);
        Assert.Contains(corruptBytes.Diagnostics, diagnostic => diagnostic.Code == "bytes.corrupt");
    }

    [Fact]
    public async Task Inspect_maps_bad_proto_and_bad_cells_to_invalid_and_data_error_states()
    {
        var service = CreateService();
        Initialize(service);
        File.WriteAllText(
            Path.Combine(_root, "Schema", "Broken.proto"),
            "syntax = \"proto3\"; message Broken {\n",
            new UTF8Encoding(false));

        var badProto = service.Inspect(Location);

        Assert.Equal(ProjectStatus.Invalid, badProto.Status);
        Assert.Equal("Invalid schema", badProto.Schema.Status);
        Assert.False(badProto.Actions.Regenerate.Enabled);
        Assert.False(badProto.Actions.Convert.Enabled);

        File.Delete(Path.Combine(_root, "Schema", "Broken.proto"));
        var create = await service.PlanCreateTableAsync(new CreateTableRequest(
            Location,
            new TableCreateIntent(
                "Hero",
                "Excel/game.xlsx",
                [
                    new SimpleFieldDefinition("name", SimpleFieldType.String),
                    new SimpleFieldDefinition("level", SimpleFieldType.Int32),
                ])));
        Apply(service, create);
        var workbookPath = Path.Combine(_root, "Excel", "game.xlsx");
        AddPendingRow(workbookPath, "hero-1", "First");
        Apply(service, await service.PlanDataPrepareAsync(new DataPrepareRequest(Location)));
        ReplaceBusinessCell(workbookPath, "level", "not-an-int");

        var badCell = service.Inspect(Location);

        Assert.Equal(ProjectStatus.DataErrors, badCell.Status);
        Assert.Contains("Data errors", badCell.Excel.Status, StringComparison.Ordinal);
        Assert.False(badCell.Actions.Convert.Enabled);
        Assert.Contains(badCell.Diagnostics, diagnostic => diagnostic.IsFailure);
    }

    [Fact]
    public async Task Live_table_with_no_export_targets_is_ready_without_bytes_and_disables_convert_truthfully()
    {
        var service = CreateService();
        Initialize(service);
        await CreateHeroAsync(service, ExportTargetSelection.Explicit([]));

        var inspection = service.Inspect(Location);

        Assert.Equal(ProjectStatus.Ready, inspection.Status);
        Assert.Equal(1, inspection.Schema.ItemCount);
        Assert.Empty(inspection.GeneratedByteTargets);
        Assert.Equal("No export targets declared", inspection.GeneratedBytes.Status);
        Assert.False(inspection.Actions.Convert.Enabled);
        Assert.Contains("No export targets", inspection.Actions.Convert.DisabledReason!, StringComparison.Ordinal);
        Assert.False(Directory.Exists(Path.Combine(_root, "Generated", "Bytes", "client")));
        Assert.False(Directory.Exists(Path.Combine(_root, "Generated", "Bytes", "server")));
    }

    [Fact]
    public void Explicit_owned_attribute_repair_is_separate_from_read_only_inspection()
    {
        if (!OperatingSystem.IsWindows())
            return;
        var service = CreateService();
        Initialize(service);
        var internalDirectory = Path.Combine(_root, ".exceldb");
        var googleDirectory = Path.Combine(_root, "Schema", "google");
        var protobufDirectory = Path.Combine(googleDirectory, "protobuf");
        var optionsPath = Path.Combine(_root, "Schema", "exceldb", "options.proto");
        File.SetAttributes(internalDirectory, File.GetAttributes(internalDirectory) & ~FileAttributes.Hidden);
        File.SetAttributes(googleDirectory, File.GetAttributes(googleDirectory) & ~FileAttributes.Hidden);
        File.SetAttributes(protobufDirectory, File.GetAttributes(protobufDirectory) & ~FileAttributes.Hidden);
        File.SetAttributes(optionsPath, File.GetAttributes(optionsPath) & ~FileAttributes.ReadOnly);

        _ = service.Inspect(Location);
        Assert.Equal((FileAttributes)0, File.GetAttributes(internalDirectory) & FileAttributes.Hidden);
        Assert.Equal((FileAttributes)0, File.GetAttributes(googleDirectory) & FileAttributes.Hidden);
        Assert.Equal((FileAttributes)0, File.GetAttributes(protobufDirectory) & FileAttributes.Hidden);
        Assert.Equal((FileAttributes)0, File.GetAttributes(optionsPath) & FileAttributes.ReadOnly);

        var report = service.RepairProjectOwnedAttributes(Location);

        Assert.True(report.Succeeded, FormatDiagnostics(report));
        Assert.NotEqual((FileAttributes)0, File.GetAttributes(internalDirectory) & FileAttributes.Hidden);
        Assert.NotEqual((FileAttributes)0, File.GetAttributes(googleDirectory) & FileAttributes.Hidden);
        Assert.NotEqual((FileAttributes)0, File.GetAttributes(protobufDirectory) & FileAttributes.Hidden);
        Assert.NotEqual((FileAttributes)0, File.GetAttributes(optionsPath) & FileAttributes.ReadOnly);
    }

    [Fact]
    public async Task Generated_csharp_artifact_and_manifest_symlinks_are_never_current_or_convertible()
    {
        var service = CreateService();
        Initialize(service);
        await CreateHeroAsync(service);
        Directory.CreateDirectory(_externalCSharp);
        var generatedRoot = Path.Combine(_root, "Generated", "CSharp");
        var artifactPath = Path.Combine(generatedRoot, "Authoring", "ExcelDbSchema.Authoring.g.cs");
        var manifestPath = Path.Combine(generatedRoot, "codegen.manifest.json");
        var artifactBytes = File.ReadAllBytes(artifactPath);
        var manifestBytes = File.ReadAllBytes(manifestPath);
        var outsideArtifact = Path.Combine(_externalCSharp, "artifact.cs");
        var outsideManifest = Path.Combine(_externalCSharp, "manifest.json");
        File.WriteAllBytes(outsideArtifact, artifactBytes);
        File.WriteAllBytes(outsideManifest, manifestBytes);
        var outsideBefore = SnapshotTree(_externalCSharp);

        File.Delete(artifactPath);
        if (!TryCreateFileLink(artifactPath, outsideArtifact))
        {
            File.WriteAllBytes(artifactPath, artifactBytes);
            return;
        }
        try
        {
            var linkedArtifact = service.Inspect(Location);
            Assert.Equal(ProjectStatus.RegenerationRequired, linkedArtifact.Status);
            Assert.Contains(linkedArtifact.Diagnostics, diagnostic =>
                diagnostic.Code == "codegen.stale"
                && diagnostic.Message.Contains("regular file", StringComparison.OrdinalIgnoreCase));
            Assert.False(linkedArtifact.Actions.Convert.Enabled);
            var convert = await service.ConvertAsync(new ConvertRequest(Location, "client"));
            Assert.False(convert.Succeeded);
            Assert.Contains(convert.Diagnostics, diagnostic => diagnostic.Code == "codegen.stale");
            AssertTreeUnchanged(outsideBefore, SnapshotTree(_externalCSharp));
        }
        finally
        {
            DeleteFileLinkIfPresent(artifactPath);
            File.WriteAllBytes(artifactPath, artifactBytes);
        }

        File.Delete(manifestPath);
        if (!TryCreateFileLink(manifestPath, outsideManifest))
        {
            File.WriteAllBytes(manifestPath, manifestBytes);
            return;
        }
        try
        {
            var linkedManifest = service.Inspect(Location);
            Assert.Equal(ProjectStatus.RegenerationRequired, linkedManifest.Status);
            Assert.Contains(linkedManifest.Diagnostics, diagnostic =>
                diagnostic.Code == "codegen.stale"
                && diagnostic.Location.EndsWith("codegen.manifest.json", StringComparison.Ordinal));
            Assert.False(linkedManifest.Actions.Convert.Enabled);
            AssertTreeUnchanged(outsideBefore, SnapshotTree(_externalCSharp));
        }
        finally
        {
            DeleteFileLinkIfPresent(manifestPath);
            File.WriteAllBytes(manifestPath, manifestBytes);
        }
    }

    [Fact]
    public void Shared_service_persists_operation_reports_in_hidden_diagnostics()
    {
        var service = CreateService();
        var plan = service.PlanInitialize(new InitializeProjectRequest(Location));

        var report = service.Apply(plan);

        Assert.True(report.Succeeded, FormatDiagnostics(report));
        var artifact = Assert.Single(report.Artifacts, item => item.Kind == "operation-report");
        Assert.True(File.Exists(artifact.Path));
        Assert.StartsWith(
            Path.Combine(_root, ".exceldb", "reports") + Path.DirectorySeparatorChar,
            artifact.Path,
            StringComparison.OrdinalIgnoreCase);
        Assert.Equal(artifact.Path, service.Inspect(Location).LatestReportPath);
        Assert.Contains("/reports/", File.ReadAllText(Path.Combine(_root, ".exceldb", ".gitignore")));
    }

    [Fact]
    public void Recovery_required_inspection_still_exposes_current_diagnostic_locations()
    {
        var service = CreateService();
        var initialize = service.Apply(service.PlanInitialize(new InitializeProjectRequest(Location)));
        Assert.True(initialize.Succeeded, FormatDiagnostics(initialize));
        var reportPath = Assert.Single(initialize.Artifacts, item => item.Kind == "operation-report").Path;
        var internalDirectory = Path.Combine(_root, ".exceldb");
        var recoveryDirectory = Path.Combine(internalDirectory, "recovery");
        File.WriteAllText(Path.Combine(recoveryDirectory, "external-bytes"), "occupied");

        var inspection = service.Inspect(Location);

        Assert.Equal(ProjectStatus.RecoveryRequired, inspection.Status);
        Assert.Equal(reportPath, inspection.LatestReportPath);
        Assert.Equal(internalDirectory, inspection.InternalDirectory);
        Assert.Equal(recoveryDirectory, inspection.RecoveryDirectory);
        Assert.Equal("occupied", File.ReadAllText(Path.Combine(recoveryDirectory, "external-bytes")));
    }

    [Fact]
    public void Invalid_project_inspection_still_exposes_current_diagnostic_locations()
    {
        var service = CreateService();
        var initialize = service.Apply(service.PlanInitialize(new InitializeProjectRequest(Location)));
        Assert.True(initialize.Succeeded, FormatDiagnostics(initialize));
        var reportPath = Assert.Single(initialize.Artifacts, item => item.Kind == "operation-report").Path;
        var internalDirectory = Path.Combine(_root, ".exceldb");
        var recoveryDirectory = Path.Combine(internalDirectory, "recovery");
        File.WriteAllText(Path.Combine(internalDirectory, "project.json"), "{ invalid json");

        var inspection = service.Inspect(Location);

        Assert.Equal(ProjectStatus.Invalid, inspection.Status);
        Assert.Equal(reportPath, inspection.LatestReportPath);
        Assert.Equal(internalDirectory, inspection.InternalDirectory);
        Assert.Equal(recoveryDirectory, inspection.RecoveryDirectory);
    }

    [Fact]
    public async Task Convert_derives_server_and_future_target_outputs_without_more_project_keys()
    {
        var service = CreateService();
        Initialize(service);
        await CreateHeroAsync(
            service,
            ExportTargetSelection.Explicit(["client", "server", "lite"]));
        AddPendingRow(Path.Combine(_root, "Excel", "game.xlsx"), "hero-1", "First");
        Apply(service, await service.PlanDataPrepareAsync(new DataPrepareRequest(Location)));

        var server = await service.ConvertAsync(new ConvertRequest(Location, "server"));
        var lite = await service.ConvertAsync(new ConvertRequest(Location, "lite"));

        Assert.True(server.Succeeded, FormatDiagnostics(server));
        Assert.True(lite.Succeeded, FormatDiagnostics(lite));
        Assert.True(File.Exists(Path.Combine(_root, "Generated", "Bytes", "server", "config.bytes")));
        Assert.True(File.Exists(Path.Combine(_root, "Generated", "Bytes", "server", "config.bytes.manifest.json")));
        Assert.True(File.Exists(Path.Combine(_root, "Generated", "Bytes", "lite", "config.bytes")));
        Assert.True(File.Exists(Path.Combine(_root, "Generated", "Bytes", "lite", "config.bytes.manifest.json")));

        using var projectJson = JsonDocument.Parse(File.ReadAllBytes(Path.Combine(_root, ".exceldb", "project.json")));
        Assert.Equal(5, projectJson.RootElement.EnumerateObject().Count());
        Assert.False(projectJson.RootElement.TryGetProperty("bytesOutput", out _));
        Assert.False(projectJson.RootElement.TryGetProperty("server", out _));

        await Assert.ThrowsAsync<ArgumentException>(async () =>
            await service.ConvertAsync(new ConvertRequest(Location, "../escape")));
        Assert.False(File.Exists(Path.Combine(_root, "escape", "config.bytes")));
    }

    [Fact]
    public void Modified_owned_system_mirror_is_blocked_until_explicit_repair()
    {
        var catalog = PackageSystemProtoCatalog.Default;
        var service = CreateService(catalog: catalog);
        Initialize(service);
        var optionsPath = Path.Combine(_root, "Schema", "exceldb", "options.proto");
        File.SetAttributes(optionsPath, File.GetAttributes(optionsPath) & ~FileAttributes.ReadOnly);
        File.WriteAllText(optionsPath, "syntax = \"proto3\"; // user edit\n", new UTF8Encoding(false));

        var inspection = service.Inspect(Location);
        var ordinary = service.PlanRepairSystemImports(new RepairSystemImportsRequest(Location, ExplicitRepair: false));
        var repair = service.PlanRepairSystemImports(new RepairSystemImportsRequest(Location, ExplicitRepair: true));

        Assert.Equal(ProjectStatus.SystemImportsConflicted, inspection.Status);
        Assert.Contains(inspection.Diagnostics, diagnostic => diagnostic.Code == "system-import.modified");
        Assert.True(ordinary.HasBlockers);
        Assert.DoesNotContain(ordinary.Mutations, mutation => Normalize(mutation.RelativePath) == "Schema/exceldb/options.proto");
        Assert.False(repair.HasBlockers, FormatDiagnostics(repair));
        Assert.Contains(repair.Mutations, mutation => Normalize(mutation.RelativePath) == "Schema/exceldb/options.proto");

        Apply(service, repair);
        Assert.True(catalog.TryGetFile("exceldb/options.proto", out var canonical));
        Assert.Equal(canonical.CanonicalBytes.ToArray(), File.ReadAllBytes(optionsPath));
        Assert.DoesNotContain(
            service.Inspect(Location).Diagnostics,
            diagnostic => diagnostic.Code == "system-import.modified");
    }

    [Fact]
    public async Task Regenerate_repairs_mirror_and_syncs_csharp_and_excel_without_touching_identity_bytes_or_policies()
    {
        var initializer = new CountingInitializer();
        var strategy = new CountingExportTargetStrategy();
        var service = CreateService(initializer, strategy);
        Initialize(service);
        await CreateHeroAsync(service);
        var workbookPath = Path.Combine(_root, "Excel", "game.xlsx");
        AddPendingRow(workbookPath, "hero-1", "Before");
        Apply(service, await service.PlanDataPrepareAsync(new DataPrepareRequest(Location)));
        ReplaceBusinessCell(workbookPath, "name", "Keep me");
        var before = Assert.Single(Assert.Single(XlsxWorkbookCodec.Read(File.ReadAllBytes(workbookPath)).Tables).Rows);
        Assert.NotNull(before.RowGuid);

        var protoPath = Path.Combine(_root, "Schema", "Hero.proto");
        var proto = File.ReadAllText(protoPath);
        var closingBrace = proto.LastIndexOf("\n}", StringComparison.Ordinal);
        Assert.True(closingBrace > 0);
        File.WriteAllText(
            protoPath,
            proto.Insert(closingBrace, "\n  int32 hp = 3;"),
            new UTF8Encoding(false));

        var mirrorPath = Path.Combine(_root, "Schema", "exceldb", "options.proto");
        File.SetAttributes(mirrorPath, File.GetAttributes(mirrorPath) & ~FileAttributes.ReadOnly);
        File.Delete(mirrorPath);
        var generatedPath = Path.Combine(_root, "Generated", "CSharp", "Authoring", "ExcelDbSchema.Authoring.g.cs");
        File.Delete(generatedPath);
        var bytesPath = Path.Combine(_root, "Generated", "Bytes", "client", "config.bytes");
        var bytesManifestPath = bytesPath + ".manifest.json";
        Directory.CreateDirectory(Path.GetDirectoryName(bytesPath)!);
        var bytesSentinel = Encoding.UTF8.GetBytes("do-not-touch-bytes");
        var manifestSentinel = Encoding.UTF8.GetBytes("do-not-touch-manifest");
        File.WriteAllBytes(bytesPath, bytesSentinel);
        File.WriteAllBytes(bytesManifestPath, manifestSentinel);
        var initializerCalls = initializer.Calls;
        var strategyCalls = strategy.Calls;

        var regenerate = await service.PlanRegenerateAsync(new RegenerateRequest(Location));

        Assert.False(regenerate.HasBlockers, FormatDiagnostics(regenerate));
        Assert.Equal(initializerCalls, initializer.Calls);
        Assert.Equal(strategyCalls, strategy.Calls);
        Assert.Contains(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == "Schema/exceldb/options.proto");
        Assert.Contains(regenerate.Mutations, mutation => mutation.Root == PlanRootKind.GeneratedCSharp);
        Assert.Contains(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == "Excel/game.xlsx");
        Assert.DoesNotContain(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath).StartsWith("Generated/Bytes/", StringComparison.Ordinal));
        Assert.DoesNotContain(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == "Schema/Hero.proto");

        Apply(service, regenerate);
        var afterWorkbook = XlsxWorkbookCodec.Read(File.ReadAllBytes(workbookPath));
        var afterTable = Assert.Single(afterWorkbook.Tables);
        var after = Assert.Single(afterTable.Rows);
        Assert.Equal(before.RowGuid, after.RowGuid);
        Assert.Equal("Keep me", after.Cells["name"].Text);
        Assert.Contains(afterTable.Columns, column => column.PropertyPath == "hp");
        Assert.True(File.Exists(mirrorPath));
        Assert.True(File.Exists(generatedPath));
        Assert.Equal(bytesSentinel, File.ReadAllBytes(bytesPath));
        Assert.Equal(manifestSentinel, File.ReadAllBytes(bytesManifestPath));
        Assert.Equal(initializerCalls, initializer.Calls);
        Assert.Equal(strategyCalls, strategy.Calls);
    }

    [Fact]
    public async Task Regenerate_recreates_the_default_workbook_and_advances_inspection_when_excel_is_empty()
    {
        var initializer = new CountingInitializer();
        var strategy = new CountingExportTargetStrategy();
        var service = CreateService(initializer, strategy);
        Initialize(service);
        await CreateHeroAsync(service);
        var workbookPath = Path.Combine(_root, "Excel", ProjectArtifactPaths.DefaultWorkbookFileName);
        File.Delete(workbookPath);
        var protoPath = Path.Combine(_root, "Schema", "Hero.proto");
        var protoBefore = File.ReadAllBytes(protoPath);
        var initializerCalls = initializer.Calls;
        var strategyCalls = strategy.Calls;

        var missing = service.Inspect(Location);
        Assert.Equal(ProjectStatus.RegenerationRequired, missing.Status);
        Assert.True(missing.Actions.Regenerate.Enabled);

        var regenerate = await service.PlanRegenerateAsync(new RegenerateRequest(Location));

        Assert.False(regenerate.HasBlockers, FormatDiagnostics(regenerate));
        Assert.Contains(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && mutation.Kind == FileMutationKind.WriteFile
            && Normalize(mutation.RelativePath) == "Excel/game.xlsx");
        Assert.DoesNotContain(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath).StartsWith("Generated/Bytes/", StringComparison.Ordinal));
        Assert.DoesNotContain(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == "Schema/Hero.proto");
        Assert.Equal(initializerCalls, initializer.Calls);
        Assert.Equal(strategyCalls, strategy.Calls);

        Apply(service, regenerate);

        var workbook = XlsxWorkbookCodec.Read(File.ReadAllBytes(workbookPath));
        Assert.Single(workbook.Tables);
        Assert.Empty(Assert.Single(workbook.Tables).Rows);
        Assert.Equal(protoBefore, File.ReadAllBytes(protoPath));
        Assert.False(File.Exists(Path.Combine(_root, "Generated", "Bytes", "client", "config.bytes")));
        Assert.Equal(initializerCalls, initializer.Calls);
        Assert.Equal(strategyCalls, strategy.Calls);
        var repaired = service.Inspect(Location);
        Assert.Equal(ProjectStatus.BytesGenerationRequired, repaired.Status);
        Assert.Equal(1, repaired.Excel.ItemCount);
    }

    [Fact]
    public async Task External_csharp_is_a_declared_plan_root_and_has_no_local_decoy_directory()
    {
        var service = CreateService();
        var initialize = service.PlanInitialize(new InitializeProjectRequest(Location, _externalCSharp));

        Assert.Equal(Path.GetFullPath(_externalCSharp), initialize.GeneratedCSharpRoot);
        Assert.Contains(initialize.Mutations, mutation => mutation.Root == PlanRootKind.GeneratedCSharp);
        Apply(service, initialize);
        Assert.False(Directory.Exists(Path.Combine(_root, "Generated", "CSharp")));

        var create = await service.PlanCreateTableAsync(new CreateTableRequest(
            Location,
            new TableCreateIntent(
                "Hero",
                "Excel/game.xlsx",
                [new SimpleFieldDefinition("name", SimpleFieldType.String)])));

        Assert.False(create.HasBlockers, FormatDiagnostics(create));
        Assert.Equal(Path.GetFullPath(_externalCSharp), create.GeneratedCSharpRoot);
        Assert.Contains(create.Mutations, mutation =>
            mutation.Root == PlanRootKind.GeneratedCSharp
            && Normalize(mutation.RelativePath) == "Authoring/ExcelDbSchema.Authoring.g.cs");
        Assert.DoesNotContain(create.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath).StartsWith("Generated/CSharp/", StringComparison.Ordinal));
        Apply(service, create);
        Assert.True(File.Exists(Path.Combine(_externalCSharp, "Authoring", "ExcelDbSchema.Authoring.g.cs")));
        Assert.True(service.Inspect(Location).GeneratedCSharp.IsExternal);
    }

    [Fact]
    public async Task Regenerate_preserves_unknown_csharp_and_unowned_codegen_collision_is_a_blocker()
    {
        var service = CreateService();
        Initialize(service);
        await CreateHeroAsync(service);
        var handwritten = Path.Combine(_root, "Generated", "CSharp", "Handwritten.cs");
        File.WriteAllText(handwritten, "// user-owned\n", new UTF8Encoding(false));

        var regenerate = await service.PlanRegenerateAsync(new RegenerateRequest(Location));

        Assert.False(regenerate.HasBlockers, FormatDiagnostics(regenerate));
        Assert.DoesNotContain(regenerate.Mutations, mutation =>
            mutation.Kind == FileMutationKind.DeleteFile
            && Normalize(mutation.RelativePath) == "Handwritten.cs");
        Apply(service, regenerate);
        Assert.Equal("// user-owned\n", File.ReadAllText(handwritten));

        using var collision = new IsolatedProject();
        var collisionService = CreateService();
        var collisionLocation = ProjectLocation.From(collision.Root);
        Apply(collisionService, collisionService.PlanInitialize(new InitializeProjectRequest(collisionLocation)));
        var collisionPath = Path.Combine(
            collision.Root,
            "Generated",
            "CSharp",
            "Authoring",
            "ExcelDbSchema.Authoring.g.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(collisionPath)!);
        File.WriteAllText(collisionPath, "// collision\n", new UTF8Encoding(false));

        var blocked = await collisionService.PlanCreateTableAsync(new CreateTableRequest(
            collisionLocation,
            new TableCreateIntent(
                "Hero",
                "Excel/game.xlsx",
                [new SimpleFieldDefinition("name", SimpleFieldType.String)])));

        Assert.True(blocked.HasBlockers);
        Assert.Contains(blocked.Diagnostics, diagnostic => diagnostic.Code == "codegen.path-collision");
        Assert.DoesNotContain(blocked.Mutations, mutation => mutation.Kind == FileMutationKind.DeleteFile);
        Assert.Equal("// collision\n", File.ReadAllText(collisionPath));
    }

    [Fact]
    public async Task Regenerate_excludes_owned_stale_and_retired_catalog_mirrors_while_planning_their_repair()
    {
        var currentCatalog = PackageSystemProtoCatalog.Default;
        var oldCatalog = CatalogSnapshot.WithChangedAndRetiredGoogleProto(currentCatalog);
        var oldService = CreateService(catalog: oldCatalog);
        Initialize(oldService);
        await CreateHeroAsync(oldService);
        Apply(oldService, await oldService.PlanRegenerateAsync(new RegenerateRequest(Location)));
        var descriptorPath = Path.Combine(_root, ".exceldb", "cache", "schema", "descriptor.pb");
        var generatedRoot = Path.Combine(_root, "Generated", "CSharp");
        var descriptorBefore = File.ReadAllBytes(descriptorPath);
        var generatedBefore = Directory.EnumerateFiles(generatedRoot, "*.cs", SearchOption.AllDirectories)
            .ToDictionary(
                path => Normalize(Path.GetRelativePath(generatedRoot, path)),
                File.ReadAllBytes,
                StringComparer.Ordinal);
        Assert.NotEmpty(generatedBefore);

        var currentService = CreateService(catalog: currentCatalog);
        var regenerate = await currentService.PlanRegenerateAsync(new RegenerateRequest(Location));

        Assert.False(regenerate.HasBlockers, FormatDiagnostics(regenerate));
        Assert.Contains(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && mutation.Kind == FileMutationKind.WriteFile
            && Normalize(mutation.RelativePath) == "Schema/google/protobuf/empty.proto");
        Assert.Contains(regenerate.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && mutation.Kind == FileMutationKind.DeleteFile
            && Normalize(mutation.RelativePath) == "Schema/google/protobuf/exceldb-retired.proto");

        Apply(currentService, regenerate);

        Assert.Equal(descriptorBefore, File.ReadAllBytes(descriptorPath));
        Assert.Equal(
            generatedBefore.Keys.Order(StringComparer.Ordinal),
            Directory.EnumerateFiles(generatedRoot, "*.cs", SearchOption.AllDirectories)
                .Select(path => Normalize(Path.GetRelativePath(generatedRoot, path)))
                .Order(StringComparer.Ordinal));
        foreach (var generated in generatedBefore)
            Assert.Equal(generated.Value, File.ReadAllBytes(Path.Combine(generatedRoot, generated.Key.Replace('/', Path.DirectorySeparatorChar))));
        Assert.True(currentCatalog.TryGetFile("google/protobuf/empty.proto", out var canonicalEmpty));
        Assert.Equal(
            canonicalEmpty.CanonicalBytes.ToArray(),
            File.ReadAllBytes(Path.Combine(_root, "Schema", "google", "protobuf", "empty.proto")));
        Assert.False(File.Exists(Path.Combine(_root, "Schema", "google", "protobuf", "exceldb-retired.proto")));
        var projectFile = Path.Combine(_root, ExcelDbProject.RelativeFilePath);
        var context = ExcelDbProject.Load(projectFile).Resolve(projectFile);
        var mirror = new SystemProtoMirror().Analyze(context, currentCatalog, explicitRepair: false);
        Assert.Equal(SystemProtoMirrorStatus.Current, mirror.Status);
        Assert.False(mirror.HasBlockers);
    }

    [Fact]
    public async Task Create_table_blocks_a_workbook_path_outside_excel_dir()
    {
        var service = CreateService();
        Initialize(service);

        var plan = await service.PlanCreateTableAsync(new CreateTableRequest(
            Location,
            new TableCreateIntent(
                "Hero",
                "Schema/game.xlsx",
                [new SimpleFieldDefinition("name", SimpleFieldType.String)])));

        Assert.True(plan.HasBlockers);
        Assert.Contains(plan.Diagnostics, diagnostic =>
            diagnostic.Code == "workbook.generate"
            && diagnostic.Message.Contains("excelDir", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(plan.Mutations, mutation =>
            mutation.Root == PlanRootKind.Project
            && Normalize(mutation.RelativePath) == "Schema/game.xlsx");
        Assert.False(File.Exists(Path.Combine(_root, "Schema", "game.xlsx")));
    }

    [Fact]
    public void Apply_rejects_a_plan_from_a_different_system_proto_catalog_before_writing()
    {
        var currentCatalog = PackageSystemProtoCatalog.Default;
        var oldCatalog = CatalogSnapshot.WithChangedAndRetiredGoogleProto(currentCatalog);
        var plan = CreateService(catalog: oldCatalog)
            .PlanInitialize(new InitializeProjectRequest(Location));

        var report = CreateService(catalog: currentCatalog).Apply(plan);

        Assert.False(report.Succeeded);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "plan.catalog-stale");
        Assert.False(File.Exists(Path.Combine(_root, ExcelDbProject.RelativeFilePath)));
        Assert.False(Directory.Exists(Path.Combine(_root, "Schema")));
    }

    [Fact]
    public void Apply_rejects_a_plan_when_the_project_configuration_changed()
    {
        var service = CreateService();
        Initialize(service);
        var plan = service.PlanConfigure(new ConfigureProjectRequest(
            Location,
            GeneratedCSharpDirectory: _externalCSharp));
        var projectFile = Path.Combine(_root, ExcelDbProject.RelativeFilePath);
        var changed = ExcelDbProject.Load(projectFile) with { GeneratedBytesDir = "Generated/Bytes-Changed" };
        File.WriteAllBytes(projectFile, changed.ToCanonicalJson());

        var report = service.Apply(plan);

        Assert.False(report.Succeeded);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "plan.config-stale");
        Assert.Equal(changed.ToCanonicalJson(), File.ReadAllBytes(projectFile));
        Assert.False(Directory.Exists(_externalCSharp));
    }

    [Fact]
    public void Apply_rejects_a_canonical_plan_that_omits_the_project_configuration_observation()
    {
        var service = CreateService();
        Initialize(service);
        var plan = service.PlanConfigure(new ConfigureProjectRequest(
            Location,
            GeneratedCSharpDirectory: _externalCSharp));
        var forged = MutationPlanCodec.Seal(plan with
        {
            Observations = plan.Observations
                .Where(static observation =>
                    observation.Root != PlanRootKind.Project
                    || Normalize(observation.RelativePath) != ExcelDbProject.RelativeFilePath)
                .ToImmutableArray(),
        });

        var report = service.Apply(forged);

        Assert.False(report.Succeeded);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "plan.config-unobserved");
        Assert.False(Directory.Exists(_externalCSharp));
    }

    [Fact]
    public void Apply_rejects_a_forged_external_generated_root_without_a_matching_config_write()
    {
        var service = CreateService();
        Initialize(service);
        var plan = service.PlanConfigure(new ConfigureProjectRequest(Location));
        var forged = MutationPlanCodec.Seal(plan with { GeneratedCSharpRoot = _externalCSharp });

        var report = service.Apply(forged);

        Assert.False(report.Succeeded);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "plan.config-candidate-invalid");
        Assert.False(Directory.Exists(_externalCSharp));
    }

    [Fact]
    public void Apply_rejects_a_plan_that_deletes_the_project_configuration()
    {
        var service = CreateService();
        Initialize(service);
        var plan = service.PlanConfigure(new ConfigureProjectRequest(
            Location,
            GeneratedCSharpDirectory: _externalCSharp));
        var forged = MutationPlanCodec.Seal(plan with
        {
            Mutations = plan.Mutations
                .Select(static mutation =>
                    mutation.Root == PlanRootKind.Project
                    && Normalize(mutation.RelativePath) == ExcelDbProject.RelativeFilePath
                        ? new FileMutation(FileMutationKind.DeleteFile, ExcelDbProject.RelativeFilePath)
                        : mutation)
                .ToImmutableArray(),
        });

        var report = service.Apply(forged);

        Assert.False(report.Succeeded);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "plan.config-candidate-invalid");
        Assert.True(File.Exists(Path.Combine(_root, ExcelDbProject.RelativeFilePath)));
        Assert.False(Directory.Exists(_externalCSharp));
    }

    private ProjectLocation Location => ProjectLocation.From(_root);

    private static ExcelDbProjectService CreateService(
        ITableInitializer? initializer = null,
        IExportTargetStrategy? strategy = null,
        ISystemProtoCatalog? catalog = null) =>
        new(
            "test-v2",
            initializer,
            strategy,
            systemProtoCatalog: catalog);

    private void Initialize(ExcelDbProjectService service) =>
        Apply(service, service.PlanInitialize(new InitializeProjectRequest(Location)));

    private async Task CreateHeroAsync(
        ExcelDbProjectService service,
        ExportTargetSelection? tableTargets = null)
    {
        var plan = await service.PlanCreateTableAsync(new CreateTableRequest(
            Location,
            new TableCreateIntent(
                "Hero",
                "Excel/game.xlsx",
                [new SimpleFieldDefinition("name", SimpleFieldType.String)],
                TableTargets: tableTargets)));
        Apply(service, plan);
    }

    private static void Apply(ExcelDbProjectService service, MutationPlan plan)
    {
        Assert.False(plan.HasBlockers, FormatDiagnostics(plan));
        var report = service.Apply(plan);
        Assert.True(report.Succeeded, FormatDiagnostics(report));
    }

    private static string FormatDiagnostics(MutationPlan plan) =>
        string.Join(Environment.NewLine, plan.Diagnostics.Select(static item => $"{item.Code}: {item.Message}"));

    private static string FormatDiagnostics(ExcelDb.Core.Diagnostics.OperationReport report) =>
        string.Join(Environment.NewLine, report.Diagnostics.Select(static item => $"{item.Code}: {item.Message}"));

    private static string Normalize(string path) => path.Replace('\\', '/');

    private static void AddPendingRow(string path, string id, string name)
    {
        var workbook = XlsxWorkbookCodec.Read(File.ReadAllBytes(path));
        var table = Assert.Single(workbook.Tables);
        var row = new WorkbookRow(
            null,
            0,
            new Dictionary<string, WorkbookCell>
            {
                ["id"] = new(id),
                ["name"] = new(name),
            }.ToImmutableDictionary(StringComparer.Ordinal),
            id);
        File.WriteAllBytes(path, XlsxWorkbookCodec.Write(workbook with
        {
            Tables = [table with { Rows = [row] }],
        }));
    }

    private static void ReplaceBusinessCell(string path, string property, string value)
    {
        var workbook = XlsxWorkbookCodec.Read(File.ReadAllBytes(path));
        var table = Assert.Single(workbook.Tables);
        var row = Assert.Single(table.Rows);
        File.WriteAllBytes(path, XlsxWorkbookCodec.Write(workbook with
        {
            Tables =
            [
                table with
                {
                    Rows = [row with { Cells = row.Cells.SetItem(property, new WorkbookCell(value)) }],
                },
            ],
        }));
    }

    private static ImmutableArray<string> SnapshotTree(string root)
    {
        if (!Directory.Exists(root))
            return [];
        return Directory.EnumerateFileSystemEntries(root, "*", SearchOption.AllDirectories)
            .Prepend(root)
            .Order(StringComparer.Ordinal)
            .Select(path =>
            {
                var relative = path == root ? "." : Normalize(Path.GetRelativePath(root, path));
                var attributes = File.GetAttributes(path);
                if ((attributes & FileAttributes.Directory) != 0)
                {
                    return $"D|{relative}|{(int)attributes}";
                }
                var info = new FileInfo(path);
                var hash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(path)));
                return $"F|{relative}|{(int)attributes}|{info.Length}|{info.LastWriteTimeUtc.Ticks}|{hash}";
            })
            .ToImmutableArray();
    }

    private static void AssertTreeUnchanged(
        ImmutableArray<string> before,
        ImmutableArray<string> after)
    {
        var removed = before.Except(after, StringComparer.Ordinal).ToArray();
        var added = after.Except(before, StringComparer.Ordinal).ToArray();
        Assert.True(
            removed.Length == 0 && added.Length == 0,
            $"Removed/changed:{Environment.NewLine}{string.Join(Environment.NewLine, removed)}" +
            $"{Environment.NewLine}Added/changed:{Environment.NewLine}{string.Join(Environment.NewLine, added)}");
    }

    private static bool TryCreateDirectoryLink(string link, string target)
    {
        try
        {
            Directory.CreateSymbolicLink(link, target);
            return true;
        }
        catch (Exception exception) when (exception is IOException
                                           or UnauthorizedAccessException
                                           or PlatformNotSupportedException)
        {
            return false;
        }
    }

    private static bool TryCreateFileLink(string link, string target)
    {
        try
        {
            File.CreateSymbolicLink(link, target);
            return true;
        }
        catch (Exception exception) when (exception is IOException
                                           or UnauthorizedAccessException
                                           or PlatformNotSupportedException)
        {
            return false;
        }
    }

    private static void DeleteLinkIfPresent(string path)
    {
        if (Directory.Exists(path)
            && File.GetAttributes(path).HasFlag(FileAttributes.ReparsePoint))
        {
            Directory.Delete(path);
        }
    }

    private static void DeleteFileLinkIfPresent(string path)
    {
        if (File.Exists(path)
            && File.GetAttributes(path).HasFlag(FileAttributes.ReparsePoint))
        {
            File.Delete(path);
        }
    }

    public void Dispose()
    {
        DeleteTree(_root);
        DeleteTree(_externalCSharp);
    }

    private static void DeleteTree(string path)
    {
        if (!Directory.Exists(path))
            return;
        foreach (var file in Directory.EnumerateFiles(path, "*", SearchOption.AllDirectories))
            File.SetAttributes(file, FileAttributes.Normal);
        Directory.Delete(path, recursive: true);
    }

    private sealed class CountingInitializer : ITableInitializer
    {
        private readonly DefaultTableInitializer _inner = new();

        public string Id => "test.counting-initializer";

        public int Calls { get; private set; }

        public void Initialize(in TableInitializationContext context, ITableDraft draft)
        {
            Calls++;
            _inner.Initialize(in context, draft);
        }
    }

    private sealed class CatalogSnapshot : ISystemProtoCatalog
    {
        private readonly IReadOnlyDictionary<string, SystemProtoFile> _byPath;

        private CatalogSnapshot(IEnumerable<SystemProtoFile> files)
        {
            Files = files.OrderBy(static file => file.LogicalPath, StringComparer.Ordinal).ToArray();
            _byPath = Files.ToDictionary(static file => file.LogicalPath, StringComparer.Ordinal);
            using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
            foreach (var file in Files)
            {
                hash.AppendData(Encoding.UTF8.GetBytes(file.LogicalPath));
                hash.AppendData([0]);
                hash.AppendData(Encoding.ASCII.GetBytes(file.Sha256));
                hash.AppendData([(byte)'\n']);
            }
            CatalogHash = Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();
        }

        public IReadOnlyList<SystemProtoFile> Files { get; }

        public string CatalogHash { get; }

        public bool TryGetFile(string logicalPath, [NotNullWhen(true)] out SystemProtoFile? file) =>
            _byPath.TryGetValue(logicalPath, out file);

        public static CatalogSnapshot WithChangedAndRetiredGoogleProto(ISystemProtoCatalog current)
        {
            var files = current.Files.Select(file =>
                string.Equals(file.LogicalPath, "google/protobuf/empty.proto", StringComparison.Ordinal)
                    ? new SystemProtoFile(
                        file.LogicalPath,
                        [.. file.CanonicalBytes.ToArray(), .. Encoding.UTF8.GetBytes("\n// old catalog payload\n")])
                    : file).ToList();
            files.Add(new SystemProtoFile(
                "google/protobuf/exceldb-retired.proto",
                Encoding.UTF8.GetBytes("syntax = \"proto3\"; package google.protobuf;\n")));
            return new CatalogSnapshot(files);
        }
    }

    private sealed class CountingExportTargetStrategy : IExportTargetStrategy
    {
        private readonly StandardClientServerExportTargetStrategy _inner = new();

        public string Id => "test.counting-targets";

        public int Calls { get; private set; }

        public void Apply(in ExportTargetStrategyContext context, IExportTargetDraft draft)
        {
            Calls++;
            _inner.Apply(in context, draft);
        }
    }

    private sealed class IsolatedProject : IDisposable
    {
        public IsolatedProject()
        {
            Root = Path.Combine(
                Path.GetTempPath(),
                "exceldb-project-service-collision",
                Guid.NewGuid().ToString("N"));
        }

        public string Root { get; }

        public void Dispose() => DeleteTree(Root);
    }
}
