#if UNITY_EDITOR || EXCELDB_DOTNET_VALIDATE
using UnityEditor;
using UnityEngine;

namespace ExcelDb.Editor.Unity
{

internal static class ExcelDbSettings
{
    [SettingsProvider]
    private static SettingsProvider Create() => new SettingsProvider("Project/ExcelDB", SettingsScope.Project)
    {
        label = "ExcelDB",
        guiHandler = _ => Draw(),
    };

    private static void Draw()
    {
        var bridge = ExcelDbUnityEditorBridge.Current;
        if (bridge is null)
        {
            EditorGUILayout.HelpBox("The ExcelDB Unity host bridge is not configured.", MessageType.Error);
            return;
        }
        if (!bridge.HasProject)
        {
            EditorGUILayout.HelpBox("Initialize ExcelDB Project first.", MessageType.Info);
            if (GUILayout.Button("Initialize")) bridge.InitializeProject();
            return;
        }

        var settings = bridge.ReadProjectSettings();
        EditorGUI.BeginChangeCheck();
        var schemaDirectory = EditorGUILayout.TextField("Schema Directory", settings.SchemaDirectory);
        var excelDirectory = EditorGUILayout.TextField("Excel Directory", settings.ExcelDirectory);
        var generatedCSharpDirectory = EditorGUILayout.TextField("Generated C# Directory", settings.GeneratedCSharpDirectory);
        var generatedBytesDirectory = EditorGUILayout.TextField("Generated Bytes Directory", settings.GeneratedBytesDirectory);
        if (EditorGUI.EndChangeCheck())
        {
            bridge.WriteProjectSettings(new UnityEditorProjectSettings(
                schemaDirectory,
                excelDirectory,
                generatedCSharpDirectory,
                generatedBytesDirectory));
        }

        EditorGUILayout.Space();
        var metadata = bridge.ReadProjectSettingsMetadata();
        using (new EditorGUI.DisabledScope(true))
        {
            EditorGUILayout.TextField("Schema Hash", metadata.SchemaHash);
            EditorGUILayout.TextField("Tool Version", metadata.ToolVersion);
        }
    }
}
}
#endif
