<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>ExcelDb.Excel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExcelDb.Core\ExcelDb.Core.csproj" />
  </ItemGroup>

</Project>
